{
 "title": "libp2p Autorelay",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relay Finder Status",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "libp2p_autorelay_status{instance=~\"$instance\"}",
     "legendFormat": "active"
    }
   ]
  },
  { "title": "Reservations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Current Reservations",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_reservations_opened_total{instance=~\"$instance\"} -  libp2p_autorelay_reservations_closed_total{instance=~\"$instance\"}",
     "legendFormat": "current reservations"
    },
    {
     "expr": "libp2p_autorelay_desired_reservations{instance=~\"$instance\"}",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Reservation Requests Outcome",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "increase(libp2p_autorelay_reservation_requests_outcome_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{request_type}}: {{outcome}}"
    }
   ]
  },
  { "title": "Candidates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Candidate Loop State",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "libp2p_autorelay_candidate_loop_state{instance=~\"$instance\"}",
     "legendFormat": "state"
    }
   ]
  },
  {
   "title": "Current Candidates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 1, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_candidates_total{type=\"added\",instance=~\"$instance\"} - ignoring(type) libp2p_autorelay_candidates_total{type=\"removed\",instance=~\"$instance\"}",
     "legendFormat": "num candidates"
    }
   ]
  },
  {
   "title": "Candidates Circuit V2 Support",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(libp2p_autorelay_candidates_circuit_v2_support_total{instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{support}}"
    }
   ]
  },
  {
   "title": "Next Old Candidate Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_scheduled_work_time{work_type=\"old candidate check\",instance=~\"$instance\"} * 1000\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next Allowed Call to peer source",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(libp2p_autorelay_scheduled_work_time{work_type=\"allowed peer source call\",instance=~\"$instance\"} - time()) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Relay Addresses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Relay Addresses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_autorelay_relay_addresses_count{instance=~\"$instance\"}",
     "legendFormat": "num addresses"
    }
   ]
  },
  {
   "title": "Relay Addresses Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "increase(libp2p_autorelay_relay_addresses_updated_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "update triggered"
    }
   ]
  }
 ]
}