version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errname
    - errorlint
    - godot
    - gosec
    - misspell
    - revive
    - whitespace
    - nakedret
  settings:
    nakedret:
      max-func-lines: 0 # Disallow function with naked returns.
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: QF1008
      - linters:
          - revive
        path: _test\.go
        text: unused-parameter
      - linters:
          - revive
        path: _test\.go
        text: context-as-argument
      - linters:
          - gosec
        path: _test\.go
        text: weak random number generator
      - linters:
          - revive
        text: if-return
      - linters:
          - gosec
        text: overflow conversion int64 -> uint64
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
