export {signPreparedChange, signDocumentChange, createGenesisChange, createDocumentChange} from './change'
export type {SignDocumentChangeInput, CreateDocumentChangeInput} from './change'
export {createSeedClient} from './client'
export type {SeedClient, SeedClientOptions, PublishDocumentInput} from './client'
export {createComment, deleteComment} from './comment'
export type {CreateCommentInput, DeleteCommentInput, CommentAttachmentBlob} from './comment'
export {createContact, updateContact, deleteContact, contactRecordIdFromBlob} from './contact'
export type {CreateContactInput, UpdateContactInput, DeleteContactInput, CreateContactResult} from './contact'
export {createCapability} from './capability'
export type {CreateCapabilityInput, CapabilityRole} from './capability'
export {createVersionRef, createTombstoneRef, createRedirectRef} from './ref'
export type {CreateVersionRefInput, CreateTombstoneRefInput, CreateRedirectRefInput} from './ref'
export {SeedClientError, SeedNetworkError, SeedValidationError} from './errors'

// Re-export key types so consumers don't need @shm/shared directly
export type {HMRequest, UnpackedHypermediaId} from '@shm/shared/hm-types'
