name: CI setup

description: |
  Sets up the CI environment for the project

inputs:
  matrix-os:
    description: "The Current OS"
    required: true
  # matrix-target:
  #   description: "The Current Target"
  #   required: true
  # matrix-goarch:
  #   description: "The Current Go Arch"
  #   required: true

runs:
  using: "composite"

  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.4"

    - name: "Install native packages"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf rpm libc6 python3 build-essential sqlite3 libsqlite3-dev flatpak flatpak-builder elfutils libnss3 libnspr4 libasound2t64 libnotify4 libpcre3 libpulse0 libxss1 libxtst6 squashfs-tools cmake libgomp1
        # Snap-related packages temporarily disabled - focusing on flatpak
        # sudo apt-get install -y snapd
        # sudo snap install snapcraft --classic --channel=7.x/stable
        # sudo snap install multipass
      shell: bash

    - name: "Install Vulkan dev packages (Linux)"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y libvulkan-dev glslc
      shell: bash

    - name: "Install Vulkan SDK (Windows)"
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        $vulkanVersion = "1.4.313.2"
        curl.exe -o $env:RUNNER_TEMP/VulkanSDK-Installer.exe -L "https://sdk.lunarg.com/sdk/download/$vulkanVersion/windows/vulkansdk-windows-X64-$vulkanVersion.exe"
        & "$env:RUNNER_TEMP\VulkanSDK-Installer.exe" --accept-licenses --default-answer --confirm-command install
        Add-Content $env:GITHUB_ENV "VULKAN_SDK=C:\VulkanSDK\$vulkanVersion"
        Add-Content $env:GITHUB_PATH "C:\VulkanSDK\$vulkanVersion\Bin"

    - name: "Build llama.cpp (Linux)"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        cd backend/util/llama-go
        BUILD_TYPE=vulkan CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" make libbinding.a
      shell: bash

    - name: "Build llama.cpp (macOS)"
      if: startsWith(inputs.matrix-os, 'macos')
      run: |
        cd backend/util/llama-go
        BUILD_TYPE=metal CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" make libbinding.a
      shell: bash

    - name: "Build llama.cpp (Windows)"
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== START: Build llama.cpp (Windows) ==="
        Write-Host "PowerShell version: $($PSVersionTable.PSVersion)"
        Write-Host "Current directory: $(Get-Location)"

        cd backend/util/llama-go
        Write-Host "Changed to: $(Get-Location)"

        # Build llama.cpp with CMake using MSVC
        # Disable tools/tests/examples/server to only build core libraries
        Write-Host "=== Running CMake configure ==="
        cmake -B build -S llama.cpp -DGGML_VULKAN=ON -DBUILD_SHARED_LIBS=OFF -DLLAMA_CURL=OFF -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_TOOLS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_SERVER=OFF -DCMAKE_BUILD_TYPE=Release
        if ($LASTEXITCODE -ne 0) {
          Write-Host "ERROR: CMake configure failed with exit code $LASTEXITCODE"
          exit 1
        }
        Write-Host "CMake configure succeeded"

        # Build with --verbose flag (temporary for debugging)
        Write-Host "=== Running CMake build ==="
        cmake --build build --config Release --verbose -j $env:NUMBER_OF_PROCESSORS
        if ($LASTEXITCODE -ne 0) {
          Write-Host "ERROR: CMake build failed with exit code $LASTEXITCODE"
          exit 1
        }
        Write-Host "CMake build succeeded"

        Write-Host "=== Copying static libraries ==="
        # Copy static libraries with Unix-style naming for CGO compatibility
        # CGO looks for lib<name>.a files, so we rename .lib to .a
        Copy-Item build/src/Release/llama.lib -Destination libllama.a
        Write-Host "  Copied llama.lib"
        Copy-Item build/ggml/src/Release/ggml.lib -Destination libggml.a
        Write-Host "  Copied ggml.lib"
        Copy-Item build/ggml/src/Release/ggml-base.lib -Destination libggml-base.a
        Write-Host "  Copied ggml-base.lib"
        Copy-Item build/ggml/src/Release/ggml-cpu.lib -Destination libggml-cpu.a
        Write-Host "  Copied ggml-cpu.lib"
        Copy-Item build/ggml/src/ggml-vulkan/Release/ggml-vulkan.lib -Destination libggml-vulkan.a
        Write-Host "  Copied ggml-vulkan.lib"
        Copy-Item build/common/Release/common.lib -Destination libcommon.a
        Write-Host "  Copied common.lib"

        # Copy Vulkan SDK library for linking
        Write-Host "=== Copying Vulkan SDK library ==="
        Write-Host "VULKAN_SDK = $env:VULKAN_SDK"
        $vulkanLibPath = "$env:VULKAN_SDK\Lib\vulkan-1.lib"
        Write-Host "Looking for: $vulkanLibPath"
        if (Test-Path $vulkanLibPath) {
          Write-Host "Found vulkan-1.lib, copying..."
          Copy-Item $vulkanLibPath -Destination libvulkan-1.a
          Write-Host "  Copied vulkan-1.lib"
        } else {
          Write-Host "ERROR: vulkan-1.lib not found at $vulkanLibPath"
          Write-Host "Listing Vulkan SDK directory:"
          if (Test-Path $env:VULKAN_SDK) {
            Get-ChildItem -Recurse $env:VULKAN_SDK -Include "*.lib" | Select-Object -First 20
          } else {
            Write-Host "VULKAN_SDK directory does not exist!"
          }
          exit 1
        }

        # Note: We do NOT create libbinding.a on Windows.
        # CGO compiles wrapper.cpp directly, so linking libbinding.a would cause
        # "multiple definition" errors for symbols like llama_wrapper_init_logging.

        Write-Host "=== Verifying all libraries ==="
        $libs = @("libllama.a", "libggml.a", "libggml-base.a", "libggml-cpu.a", "libggml-vulkan.a", "libcommon.a", "libvulkan-1.a")
        $allFound = $true
        foreach ($lib in $libs) {
          if (!(Test-Path $lib)) {
            Write-Host "ERROR: Missing library: $lib"
            $allFound = $false
          } else {
            $size = (Get-Item $lib).Length
            Write-Host "  $lib - $size bytes"
          }
        }

        if (-not $allFound) {
          Write-Host "ERROR: Some libraries are missing!"
          exit 1
        }

        Write-Host "All libraries built successfully"
        Write-Host "=== END: Build llama.cpp (Windows) - SUCCESS ==="
        exit 0

    # Additional packages for Flatpak building

    - name: "Setup Flatpak"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        # Setup Flatpak with flathub repository
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

        # Install Electron BaseApp for flatpak builds
        sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp//24.08

        # Snapcraft setup temporarily disabled - focusing on flatpak
        # echo "SNAPCRAFT_BUILD_ENVIRONMENT=host" >> $GITHUB_ENV
      shell: bash

    - name: Setup cache Ubuntu
      uses: actions/cache@v3
      if: inputs.matrix-os == 'ubuntu-latest'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Setup cache Macos
      uses: actions/cache@v3
      if: startsWith(inputs.matrix.os, 'macos')
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Debug - Before cache setup (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: About to run Setup cache Windows ==="
        Write-Host "Current directory: $(Get-Location)"
        exit 0

    - name: Setup cache Windows
      uses: actions/cache@v3
      if: inputs.matrix-os == 'windows-2025'
      continue-on-error: true
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Debug - After cache setup (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: Cache setup completed (or skipped with error) ==="
        exit 0

    - name: Debug - Before pnpm (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: About to run Install pnpm ==="
        exit 0

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      continue-on-error: true

    - name: Debug - After pnpm setup (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: pnpm setup completed (or failed) ==="
        Write-Host "pnpm version: $(pnpm --version 2>&1)"
        exit 0

    - name: Debug - Before Node.js (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: About to run Install Node.js 20 ==="
        exit 0

    - name: Install Node.js 20
      uses: actions/setup-node@v4
      continue-on-error: true
      with:
        node-version: 20
        cache: "pnpm"

    - name: Debug - After node setup (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: Node.js setup completed (or failed) ==="
        Write-Host "node version: $(node --version 2>&1)"
        Write-Host "npm version: $(npm --version 2>&1)"
        exit 0

    - name: Debug - Before pnpm install (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: About to run pnpm install ==="
        exit 0

    - name: Install Frontend Dependencies
      continue-on-error: true
      run: |
        echo "=== TRACE: Running pnpm install --frozen-lockfile ==="
        pnpm install --frozen-lockfile
        echo "=== TRACE: pnpm install completed with exit code $? ==="
      shell: bash

    - name: Debug - ci-setup complete (Windows)
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        Write-Host "=== TRACE: ci-setup action completed successfully ==="
        Write-Host "=== END OF CI-SETUP ==="
        exit 0
