name: CI setup

description: |
  Sets up the CI environment for the project

inputs:
  matrix-os:
    description: "The Current OS"
    required: true
  # matrix-target:
  #   description: "The Current Target"
  #   required: true
  # matrix-goarch:
  #   description: "The Current Go Arch"
  #   required: true

runs:
  using: "composite"

  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.4"

    - name: "Install native packages"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf rpm libc6 python3 build-essential sqlite3 libsqlite3-dev flatpak flatpak-builder elfutils libnss3 libnspr4 libasound2t64 libnotify4 libpcre3 libpulse0 libxss1 libxtst6 squashfs-tools cmake libgomp1
        # Snap-related packages temporarily disabled - focusing on flatpak
        # sudo apt-get install -y snapd
        # sudo snap install snapcraft --classic --channel=7.x/stable
        # sudo snap install multipass
      shell: bash

    - name: "Install Vulkan dev packages (Linux)"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y libvulkan-dev glslc
      shell: bash

    - name: "Install Vulkan SDK (Windows)"
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        $vulkanVersion = "1.4.313.2"
        curl.exe -o $env:RUNNER_TEMP/VulkanSDK-Installer.exe -L "https://sdk.lunarg.com/sdk/download/$vulkanVersion/windows/vulkansdk-windows-X64-$vulkanVersion.exe"
        & "$env:RUNNER_TEMP\VulkanSDK-Installer.exe" --accept-licenses --default-answer --confirm-command install
        Add-Content $env:GITHUB_ENV "VULKAN_SDK=C:\VulkanSDK\$vulkanVersion"
        Add-Content $env:GITHUB_PATH "C:\VulkanSDK\$vulkanVersion\Bin"

    - name: "Build llama.cpp (Linux)"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        cd backend/util/llama-go
        BUILD_TYPE=vulkan CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" make libbinding.a
      shell: bash

    - name: "Build llama.cpp (macOS)"
      if: startsWith(inputs.matrix-os, 'macos')
      run: |
        cd backend/util/llama-go
        BUILD_TYPE=metal CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" make libbinding.a
      shell: bash

    - name: "Build llama.cpp (Windows)"
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"

        cd backend/util/llama-go
        Write-Host "Working directory: $(Get-Location)"

        # Build llama.cpp with CMake using MSVC
        Write-Host "=== Running CMake configure ==="
        cmake -B build -S llama.cpp `
          -DGGML_VULKAN=ON `
          -DBUILD_SHARED_LIBS=OFF `
          -DLLAMA_CURL=OFF `
          -DCMAKE_BUILD_TYPE=Release

        Write-Host "=== Running CMake build ==="
        cmake --build build --config Release -j $env:NUMBER_OF_PROCESSORS

        Write-Host "=== Copying static libraries ==="
        # Copy static libraries with Unix-style naming for CGO compatibility
        # CGO looks for lib<name>.a files, so we rename .lib to .a
        Copy-Item build/src/Release/llama.lib -Destination libllama.a
        Copy-Item build/ggml/src/Release/ggml.lib -Destination libggml.a
        Copy-Item build/ggml/src/Release/ggml-base.lib -Destination libggml-base.a
        Copy-Item build/ggml/src/Release/ggml-cpu.lib -Destination libggml-cpu.a
        Copy-Item build/ggml/src/ggml-vulkan/Release/ggml-vulkan.lib -Destination libggml-vulkan.a
        Copy-Item build/common/Release/common.lib -Destination libcommon.a

        # Copy Vulkan SDK library for linking
        Write-Host "=== Copying Vulkan SDK library ==="
        Write-Host "VULKAN_SDK = $env:VULKAN_SDK"
        $vulkanLibPath = "$env:VULKAN_SDK\Lib\vulkan-1.lib"
        Write-Host "Looking for: $vulkanLibPath"
        if (Test-Path $vulkanLibPath) {
          Write-Host "Found vulkan-1.lib, copying..."
          Copy-Item $vulkanLibPath -Destination libvulkan-1.a
        } else {
          Write-Host "ERROR: vulkan-1.lib not found at $vulkanLibPath"
          Write-Host "Listing Vulkan SDK directory:"
          if (Test-Path $env:VULKAN_SDK) {
            Get-ChildItem -Recurse $env:VULKAN_SDK -Include "*.lib" | Select-Object -First 20
          } else {
            Write-Host "VULKAN_SDK directory does not exist!"
          }
          exit 1
        }

        # Note: We do NOT create libbinding.a on Windows.
        # CGO compiles wrapper.cpp directly, so linking libbinding.a would cause
        # "multiple definition" errors for symbols like llama_wrapper_init_logging.

        Write-Host "=== Verifying all libraries ==="
        $libs = @("libllama.a", "libggml.a", "libggml-base.a", "libggml-cpu.a", "libggml-vulkan.a", "libcommon.a", "libvulkan-1.a")
        foreach ($lib in $libs) {
          if (!(Test-Path $lib)) {
            Write-Error "Missing library: $lib"
            exit 1
          }
          $size = (Get-Item $lib).Length
          Write-Host "  $lib - $size bytes"
        }
        Write-Host "All libraries built successfully"

    # Additional packages for Flatpak building

    - name: "Setup Flatpak"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        # Setup Flatpak with flathub repository
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

        # Install Electron BaseApp for flatpak builds
        sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp//24.08

        # Snapcraft setup temporarily disabled - focusing on flatpak
        # echo "SNAPCRAFT_BUILD_ENVIRONMENT=host" >> $GITHUB_ENV
      shell: bash

    - name: Setup cache Ubuntu
      uses: actions/cache@v3
      if: inputs.matrix-os == 'ubuntu-latest'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Setup cache Macos
      uses: actions/cache@v3
      if: startsWith(inputs.matrix.os, 'macos')
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Setup cache Windows
      uses: actions/cache@v3
      if: inputs.matrix-os == 'windows-2025'
      continue-on-error: true
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Debug - After cache setup
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: Write-Host "=== Cache setup completed (or skipped with error) ==="

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      continue-on-error: true

    - name: Debug - After pnpm setup
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: Write-Host "=== pnpm setup completed (or failed) ==="

    - name: Install Node.js 20
      uses: actions/setup-node@v4
      continue-on-error: true
      with:
        node-version: 20
        cache: "pnpm"

    - name: Debug - After node setup
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: Write-Host "=== Node.js setup completed (or failed) ==="

    - name: Install Frontend Dependencies
      continue-on-error: true
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Debug - ci-setup complete
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: Write-Host "=== ci-setup action completed successfully ==="
