name: CI setup

description: |
  Sets up the CI environment for the project

inputs:
  matrix-os:
    description: "The Current OS"
    required: true
  # matrix-target:
  #   description: "The Current Target"
  #   required: true
  # matrix-goarch:
  #   description: "The Current Go Arch"
  #   required: true

runs:
  using: "composite"

  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.4"

    - name: "Install native packages"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf rpm libc6 python3 build-essential sqlite3 libsqlite3-dev flatpak flatpak-builder elfutils libnss3 libnspr4 libasound2t64 libnotify4 libpcre3 libpulse0 libxss1 libxtst6 squashfs-tools cmake libgomp1
        # Snap-related packages temporarily disabled - focusing on flatpak
        # sudo apt-get install -y snapd
        # sudo snap install snapcraft --classic --channel=7.x/stable
        # sudo snap install multipass
      shell: bash

    - name: "Install Vulkan dev packages (Linux)"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y libvulkan-dev glslc
      shell: bash

    - name: "Install Vulkan SDK (Windows)"
      if: inputs.matrix-os == 'windows-2025'
      shell: powershell
      run: |
        $vulkanVersion = "1.4.313.2"
        curl.exe -o $env:RUNNER_TEMP/VulkanSDK-Installer.exe -L "https://sdk.lunarg.com/sdk/download/$vulkanVersion/windows/vulkansdk-windows-X64-$vulkanVersion.exe"
        & "$env:RUNNER_TEMP\VulkanSDK-Installer.exe" --accept-licenses --default-answer --confirm-command install
        Add-Content $env:GITHUB_ENV "VULKAN_SDK=C:\VulkanSDK\$vulkanVersion"
        Add-Content $env:GITHUB_PATH "C:\VulkanSDK\$vulkanVersion\Bin"

    - name: "Build llama.cpp (Linux)"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        cd backend/util/llama-go
        BUILD_TYPE=vulkan CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" make libbinding.a
      shell: bash

    - name: "Build llama.cpp (macOS)"
      if: startsWith(inputs.matrix-os, 'macos')
      run: |
        cd backend/util/llama-go
        BUILD_TYPE=metal CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" make libbinding.a
      shell: bash

    - name: "Build llama.cpp (Windows)"
      if: inputs.matrix-os == 'windows-2025'
      shell: bash
      run: |
        set -e
        cd backend/util/llama-go

        # Build llama.cpp with CMake using MinGW for ABI compatibility with CGO
        cmake -G "MinGW Makefiles" -B build -S llama.cpp \
          -DGGML_VULKAN=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DLLAMA_CURL=OFF \
          -DLLAMA_BUILD_TESTS=OFF \
          -DLLAMA_BUILD_TOOLS=OFF \
          -DLLAMA_BUILD_EXAMPLES=OFF \
          -DLLAMA_BUILD_SERVER=OFF \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_COMPILER=g++

        cmake --build build --config Release -j $(nproc)

        # Copy static libraries (MinGW output paths differ from MSVC)
        cp build/src/libllama.a ./libllama.a
        cp build/ggml/src/ggml.a ./libggml.a
        cp build/ggml/src/ggml-base.a ./libggml-base.a
        cp build/ggml/src/ggml-cpu.a ./libggml-cpu.a
        cp build/ggml/src/ggml-vulkan/ggml-vulkan.a ./libggml-vulkan.a
        cp build/common/libcommon.a ./libcommon.a
        cp "$VULKAN_SDK/Lib/vulkan-1.lib" ./libvulkan-1.a

        # Verify all libraries exist
        for lib in libllama.a libggml.a libggml-base.a libggml-cpu.a libggml-vulkan.a libcommon.a libvulkan-1.a; do
          [ -f "$lib" ] || { echo "ERROR: Missing $lib"; exit 1; }
        done
        echo "All llama.cpp libraries built successfully"

    # Additional packages for Flatpak building

    - name: "Setup Flatpak"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        # Setup Flatpak with flathub repository
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

        # Install Electron BaseApp for flatpak builds
        sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp//24.08

        # Snapcraft setup temporarily disabled - focusing on flatpak
        # echo "SNAPCRAFT_BUILD_ENVIRONMENT=host" >> $GITHUB_ENV
      shell: bash

    - name: Setup cache Ubuntu
      uses: actions/cache@v3
      if: inputs.matrix-os == 'ubuntu-latest'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Setup cache Macos
      uses: actions/cache@v3
      if: startsWith(inputs.matrix.os, 'macos')
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Setup cache Windows
      uses: actions/cache@v3
      if: inputs.matrix-os == 'windows-2025'
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - name: Install Frontend Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
