name: CI setup

description: |
  Sets up the CI environment for the project

inputs:
  matrix-os:
    description: "The Current OS"
    required: true
  # matrix-target:
  #   description: "The Current Target"
  #   required: true
  # matrix-goarch:
  #   description: "The Current Go Arch"
  #   required: true

runs:
  using: "composite"

  steps:
    - name: "Setup Go"
      uses: actions/setup-go@v5
      with:
        go-version: "1.25.2"

    - name: "Install native packages"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-12 g++-12
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libayatana-appindicator3-dev librsvg2-dev patchelf rpm libc6 python3 build-essential sqlite3 libsqlite3-dev flatpak flatpak-builder elfutils libnss3 libnspr4 libasound2t64 libnotify4 libpcre3 libpulse0 libxss1 libxtst6 squashfs-tools
        # Snap-related packages temporarily disabled - focusing on flatpak
        # sudo apt-get install -y snapd
        # sudo snap install snapcraft --classic --channel=7.x/stable
        # sudo snap install multipass
      shell: bash

    # Additional packages for Flatpak building

    - name: "Setup Flatpak"
      if: inputs.matrix-os == 'ubuntu-latest'
      run: |
        # Setup Flatpak with flathub repository
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

        # Install Electron BaseApp for flatpak builds
        sudo flatpak install -y flathub org.electronjs.Electron2.BaseApp//24.08

        # Snapcraft setup temporarily disabled - focusing on flatpak
        # echo "SNAPCRAFT_BUILD_ENVIRONMENT=host" >> $GITHUB_ENV
      shell: bash

    - name: Setup cache Ubuntu
      uses: actions/cache@v3
      if: inputs.matrix-os == 'ubuntu-latest'
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Setup cache Macos
      uses: actions/cache@v3
      if: startsWith(inputs.matrix.os, 'macos')
      with:
        path: |
          ~/Library/Caches/go-build
          ~/go/pkg/mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Setup cache Windows
      uses: actions/cache@v3
      if: inputs.matrix-os == 'windows-2025'
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ inputs.matrix-os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.matrix-os }}-go-

    - name: Install Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "yarn"

    - name: Install Frontend Dependencies
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false
      run: |
        yarn
      shell: bash
