// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: documents/v2alpha/documents.proto

package documents

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DocumentsClient is the client API for Documents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentsClient interface {
	// Gets a single document.
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// Gets an account's profile document.
	GetProfileDocument(ctx context.Context, in *GetProfileDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// Gets a document within the index(es) of other documents.
	GetDocumentIndex(ctx context.Context, in *GetDocumentIndexRequest, opts ...grpc.CallOption) (*GetDocumentIndexResponse, error)
	// Creates a new Document Change.
	CreateDocumentChange(ctx context.Context, in *CreateDocumentChangeRequest, opts ...grpc.CallOption) (*Document, error)
	// Immediately changes an account's profile document.
	//
	// Deprecated: Use CreateDocumentChange instead.
	ChangeProfileDocument(ctx context.Context, in *ChangeProfileDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// Immediately changes a document.
	//
	// Deprecated: Use CreateDocumentChange instead.
	ChangeDocument(ctx context.Context, in *ChangeDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	// Lists all documents. Only the most recent versions show up.
	ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
	// Lists branches of a document. Includes standalone and index branches, and any drafts for these branches
	ListDocumentBranches(ctx context.Context, in *ListDocumentBranchesRequest, opts ...grpc.CallOption) (*ListDocumentBranchesResponse, error)
	// Lists all profile documents.
	ListProfileDocuments(ctx context.Context, in *ListProfileDocumentsRequest, opts ...grpc.CallOption) (*ListProfileDocumentsResponse, error)
	// Push Local document to the gateway.
	PushDocument(ctx context.Context, in *PushDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Lists documents owned by a given account.
	ListAccountDocuments(ctx context.Context, in *ListAccountDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error)
}

type documentsClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentsClient(cc grpc.ClientConnInterface) DocumentsClient {
	return &documentsClient{cc}
}

func (c *documentsClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/GetDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) GetProfileDocument(ctx context.Context, in *GetProfileDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/GetProfileDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) GetDocumentIndex(ctx context.Context, in *GetDocumentIndexRequest, opts ...grpc.CallOption) (*GetDocumentIndexResponse, error) {
	out := new(GetDocumentIndexResponse)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/GetDocumentIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) CreateDocumentChange(ctx context.Context, in *CreateDocumentChangeRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/CreateDocumentChange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) ChangeProfileDocument(ctx context.Context, in *ChangeProfileDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/ChangeProfileDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) ChangeDocument(ctx context.Context, in *ChangeDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/ChangeDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) ListDocuments(ctx context.Context, in *ListDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/ListDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) ListDocumentBranches(ctx context.Context, in *ListDocumentBranchesRequest, opts ...grpc.CallOption) (*ListDocumentBranchesResponse, error) {
	out := new(ListDocumentBranchesResponse)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/ListDocumentBranches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) ListProfileDocuments(ctx context.Context, in *ListProfileDocumentsRequest, opts ...grpc.CallOption) (*ListProfileDocumentsResponse, error) {
	out := new(ListProfileDocumentsResponse)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/ListProfileDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) PushDocument(ctx context.Context, in *PushDocumentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/PushDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentsClient) ListAccountDocuments(ctx context.Context, in *ListAccountDocumentsRequest, opts ...grpc.CallOption) (*ListDocumentsResponse, error) {
	out := new(ListDocumentsResponse)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Documents/ListAccountDocuments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentsServer is the server API for Documents service.
// All implementations should embed UnimplementedDocumentsServer
// for forward compatibility
type DocumentsServer interface {
	// Gets a single document.
	GetDocument(context.Context, *GetDocumentRequest) (*Document, error)
	// Gets an account's profile document.
	GetProfileDocument(context.Context, *GetProfileDocumentRequest) (*Document, error)
	// Gets a document within the index(es) of other documents.
	GetDocumentIndex(context.Context, *GetDocumentIndexRequest) (*GetDocumentIndexResponse, error)
	// Creates a new Document Change.
	CreateDocumentChange(context.Context, *CreateDocumentChangeRequest) (*Document, error)
	// Immediately changes an account's profile document.
	//
	// Deprecated: Use CreateDocumentChange instead.
	ChangeProfileDocument(context.Context, *ChangeProfileDocumentRequest) (*Document, error)
	// Immediately changes a document.
	//
	// Deprecated: Use CreateDocumentChange instead.
	ChangeDocument(context.Context, *ChangeDocumentRequest) (*Document, error)
	// Lists all documents. Only the most recent versions show up.
	ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error)
	// Lists branches of a document. Includes standalone and index branches, and any drafts for these branches
	ListDocumentBranches(context.Context, *ListDocumentBranchesRequest) (*ListDocumentBranchesResponse, error)
	// Lists all profile documents.
	ListProfileDocuments(context.Context, *ListProfileDocumentsRequest) (*ListProfileDocumentsResponse, error)
	// Push Local document to the gateway.
	PushDocument(context.Context, *PushDocumentRequest) (*emptypb.Empty, error)
	// Lists documents owned by a given account.
	ListAccountDocuments(context.Context, *ListAccountDocumentsRequest) (*ListDocumentsResponse, error)
}

// UnimplementedDocumentsServer should be embedded to have forward compatible implementations.
type UnimplementedDocumentsServer struct {
}

func (UnimplementedDocumentsServer) GetDocument(context.Context, *GetDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDocumentsServer) GetProfileDocument(context.Context, *GetProfileDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfileDocument not implemented")
}
func (UnimplementedDocumentsServer) GetDocumentIndex(context.Context, *GetDocumentIndexRequest) (*GetDocumentIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDocumentIndex not implemented")
}
func (UnimplementedDocumentsServer) CreateDocumentChange(context.Context, *CreateDocumentChangeRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDocumentChange not implemented")
}
func (UnimplementedDocumentsServer) ChangeProfileDocument(context.Context, *ChangeProfileDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeProfileDocument not implemented")
}
func (UnimplementedDocumentsServer) ChangeDocument(context.Context, *ChangeDocumentRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeDocument not implemented")
}
func (UnimplementedDocumentsServer) ListDocuments(context.Context, *ListDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedDocumentsServer) ListDocumentBranches(context.Context, *ListDocumentBranchesRequest) (*ListDocumentBranchesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDocumentBranches not implemented")
}
func (UnimplementedDocumentsServer) ListProfileDocuments(context.Context, *ListProfileDocumentsRequest) (*ListProfileDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfileDocuments not implemented")
}
func (UnimplementedDocumentsServer) PushDocument(context.Context, *PushDocumentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushDocument not implemented")
}
func (UnimplementedDocumentsServer) ListAccountDocuments(context.Context, *ListAccountDocumentsRequest) (*ListDocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccountDocuments not implemented")
}

// UnsafeDocumentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentsServer will
// result in compilation errors.
type UnsafeDocumentsServer interface {
	mustEmbedUnimplementedDocumentsServer()
}

func RegisterDocumentsServer(s grpc.ServiceRegistrar, srv DocumentsServer) {
	s.RegisterService(&Documents_ServiceDesc, srv)
}

func _Documents_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/GetDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_GetProfileDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).GetProfileDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/GetProfileDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).GetProfileDocument(ctx, req.(*GetProfileDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_GetDocumentIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).GetDocumentIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/GetDocumentIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).GetDocumentIndex(ctx, req.(*GetDocumentIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_CreateDocumentChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).CreateDocumentChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/CreateDocumentChange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).CreateDocumentChange(ctx, req.(*CreateDocumentChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_ChangeProfileDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeProfileDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).ChangeProfileDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/ChangeProfileDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).ChangeProfileDocument(ctx, req.(*ChangeProfileDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_ChangeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).ChangeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/ChangeDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).ChangeDocument(ctx, req.(*ChangeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/ListDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).ListDocuments(ctx, req.(*ListDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_ListDocumentBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocumentBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).ListDocumentBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/ListDocumentBranches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).ListDocumentBranches(ctx, req.(*ListDocumentBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_ListProfileDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfileDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).ListProfileDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/ListProfileDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).ListProfileDocuments(ctx, req.(*ListProfileDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_PushDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).PushDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/PushDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).PushDocument(ctx, req.(*PushDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Documents_ListAccountDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentsServer).ListAccountDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Documents/ListAccountDocuments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentsServer).ListAccountDocuments(ctx, req.(*ListAccountDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Documents_ServiceDesc is the grpc.ServiceDesc for Documents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Documents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.seed.documents.v2alpha.Documents",
	HandlerType: (*DocumentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocument",
			Handler:    _Documents_GetDocument_Handler,
		},
		{
			MethodName: "GetProfileDocument",
			Handler:    _Documents_GetProfileDocument_Handler,
		},
		{
			MethodName: "GetDocumentIndex",
			Handler:    _Documents_GetDocumentIndex_Handler,
		},
		{
			MethodName: "CreateDocumentChange",
			Handler:    _Documents_CreateDocumentChange_Handler,
		},
		{
			MethodName: "ChangeProfileDocument",
			Handler:    _Documents_ChangeProfileDocument_Handler,
		},
		{
			MethodName: "ChangeDocument",
			Handler:    _Documents_ChangeDocument_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _Documents_ListDocuments_Handler,
		},
		{
			MethodName: "ListDocumentBranches",
			Handler:    _Documents_ListDocumentBranches_Handler,
		},
		{
			MethodName: "ListProfileDocuments",
			Handler:    _Documents_ListProfileDocuments_Handler,
		},
		{
			MethodName: "PushDocument",
			Handler:    _Documents_PushDocument_Handler,
		},
		{
			MethodName: "ListAccountDocuments",
			Handler:    _Documents_ListAccountDocuments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "documents/v2alpha/documents.proto",
}

// MergeClient is the client API for Merge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MergeClient interface {
	// Merge changes and publishes.
	MergeChanges(ctx context.Context, in *MergeChangesRequest, opts ...grpc.CallOption) (*Document, error)
	// Rebase changes
	RebaseChanges(ctx context.Context, in *RebaseChangesRequest, opts ...grpc.CallOption) (*Document, error)
}

type mergeClient struct {
	cc grpc.ClientConnInterface
}

func NewMergeClient(cc grpc.ClientConnInterface) MergeClient {
	return &mergeClient{cc}
}

func (c *mergeClient) MergeChanges(ctx context.Context, in *MergeChangesRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Merge/MergeChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mergeClient) RebaseChanges(ctx context.Context, in *RebaseChangesRequest, opts ...grpc.CallOption) (*Document, error) {
	out := new(Document)
	err := c.cc.Invoke(ctx, "/com.seed.documents.v2alpha.Merge/RebaseChanges", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MergeServer is the server API for Merge service.
// All implementations should embed UnimplementedMergeServer
// for forward compatibility
type MergeServer interface {
	// Merge changes and publishes.
	MergeChanges(context.Context, *MergeChangesRequest) (*Document, error)
	// Rebase changes
	RebaseChanges(context.Context, *RebaseChangesRequest) (*Document, error)
}

// UnimplementedMergeServer should be embedded to have forward compatible implementations.
type UnimplementedMergeServer struct {
}

func (UnimplementedMergeServer) MergeChanges(context.Context, *MergeChangesRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeChanges not implemented")
}
func (UnimplementedMergeServer) RebaseChanges(context.Context, *RebaseChangesRequest) (*Document, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebaseChanges not implemented")
}

// UnsafeMergeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MergeServer will
// result in compilation errors.
type UnsafeMergeServer interface {
	mustEmbedUnimplementedMergeServer()
}

func RegisterMergeServer(s grpc.ServiceRegistrar, srv MergeServer) {
	s.RegisterService(&Merge_ServiceDesc, srv)
}

func _Merge_MergeChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeServer).MergeChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Merge/MergeChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeServer).MergeChanges(ctx, req.(*MergeChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Merge_RebaseChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebaseChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MergeServer).RebaseChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.seed.documents.v2alpha.Merge/RebaseChanges",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MergeServer).RebaseChanges(ctx, req.(*RebaseChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Merge_ServiceDesc is the grpc.ServiceDesc for Merge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Merge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.seed.documents.v2alpha.Merge",
	HandlerType: (*MergeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MergeChanges",
			Handler:    _Merge_MergeChanges_Handler,
		},
		{
			MethodName: "RebaseChanges",
			Handler:    _Merge_RebaseChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "documents/v2alpha/documents.proto",
}
