// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.24.4
// source: documents/v3alpha/access_control.proto

package documents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	// Invalid default value.
	Role_ROLE_UNSPECIFIED Role = 0
	// Has write access to the document
	Role_WRITER Role = 2
	// Grants full authority over the key,
	// including the idea to act on behalf of the issuing key.
	Role_AGENT Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		2: "WRITER",
		3: "AGENT",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"WRITER":           2,
		"AGENT":            3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_documents_v3alpha_access_control_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_documents_v3alpha_access_control_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_documents_v3alpha_access_control_proto_rawDescGZIP(), []int{0}
}

// Request to list capabilities.
type ListCapabilitiesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Account for which to list the capabilities.
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Required. Path within the account to list the capabilities for.
	// Empty string means root document.
	// String "*" means all documents.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Optional. By default all capabilities that match the path are returned,
	// even if they were issued for some parent path.
	// If this field is true, only capabilities that match the path exactly are returned.
	IgnoreInherited bool `protobuf:"varint,3,opt,name=ignore_inherited,json=ignoreInherited,proto3" json:"ignore_inherited,omitempty"`
	// Optional. Number of capabilities to return in the response.
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Page token to continue listing capabilities.
	PageToken     string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesRequest) Reset() {
	*x = ListCapabilitiesRequest{}
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesRequest) ProtoMessage() {}

func (x *ListCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_access_control_proto_rawDescGZIP(), []int{0}
}

func (x *ListCapabilitiesRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ListCapabilitiesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListCapabilitiesRequest) GetIgnoreInherited() bool {
	if x != nil {
		return x.IgnoreInherited
	}
	return false
}

func (x *ListCapabilitiesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCapabilitiesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Response to list capabilities.
type ListCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of capabilities.
	Capabilities []*Capability `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Token for the next page, if any.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesResponse) Reset() {
	*x = ListCapabilitiesResponse{}
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesResponse) ProtoMessage() {}

func (x *ListCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_access_control_proto_rawDescGZIP(), []int{1}
}

func (x *ListCapabilitiesResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ListCapabilitiesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request to list capabilities for a specific delegate.
type ListCapabilitiesForDelegateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the delegate to list capabilities for.
	Delegate string `protobuf:"bytes,1,opt,name=delegate,proto3" json:"delegate,omitempty"`
	// Optional. Number of capabilities to return in the response.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Page token to continue listing capabilities.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesForDelegateRequest) Reset() {
	*x = ListCapabilitiesForDelegateRequest{}
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesForDelegateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesForDelegateRequest) ProtoMessage() {}

func (x *ListCapabilitiesForDelegateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesForDelegateRequest.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesForDelegateRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_access_control_proto_rawDescGZIP(), []int{2}
}

func (x *ListCapabilitiesForDelegateRequest) GetDelegate() string {
	if x != nil {
		return x.Delegate
	}
	return ""
}

func (x *ListCapabilitiesForDelegateRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCapabilitiesForDelegateRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Request to create a new capability.
type CreateCapabilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Name of the key to use for signing the capability.
	SigningKeyName string `protobuf:"bytes,1,opt,name=signing_key_name,json=signingKeyName,proto3" json:"signing_key_name,omitempty"`
	// Required. Account ID to which this capability is delegated.
	Delegate string `protobuf:"bytes,2,opt,name=delegate,proto3" json:"delegate,omitempty"`
	// Required. Account ID to which this capability gives access.
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// Required. Path within the account that this capability grants access to.
	// Empty string means root document.
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// Required. Role that this capability grants to the delegate.
	// If capability is nested, the role cannot be higher than the role of any ancestor capability.
	Role Role `protobuf:"varint,5,opt,name=role,proto3,enum=com.seed.documents.v3alpha.Role" json:"role,omitempty"`
	// Optional. By default capabilities give access to the path recursively.
	// This flag can be used to restrict the capability only to specific path.
	NoRecursive bool `protobuf:"varint,6,opt,name=no_recursive,json=noRecursive,proto3" json:"no_recursive,omitempty"`
	// Optional. Short, user-provided label for the capability for user's convenience to identify them later.
	// The label is public and cannot be changed.
	Label         string `protobuf:"bytes,7,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCapabilityRequest) Reset() {
	*x = CreateCapabilityRequest{}
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCapabilityRequest) ProtoMessage() {}

func (x *CreateCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCapabilityRequest.ProtoReflect.Descriptor instead.
func (*CreateCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_access_control_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCapabilityRequest) GetSigningKeyName() string {
	if x != nil {
		return x.SigningKeyName
	}
	return ""
}

func (x *CreateCapabilityRequest) GetDelegate() string {
	if x != nil {
		return x.Delegate
	}
	return ""
}

func (x *CreateCapabilityRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateCapabilityRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateCapabilityRequest) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *CreateCapabilityRequest) GetNoRecursive() bool {
	if x != nil {
		return x.NoRecursive
	}
	return false
}

func (x *CreateCapabilityRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Request to get a single capability.
type GetCapabilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. ID of the capability to get.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilityRequest) Reset() {
	*x = GetCapabilityRequest{}
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilityRequest) ProtoMessage() {}

func (x *GetCapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilityRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilityRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_access_control_proto_rawDescGZIP(), []int{4}
}

func (x *GetCapabilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Capability is an unforgeable token that grants access to a specific path within an account.
type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of this capability.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the account that issued the capability.
	Issuer string `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// ID of the account that the capability is delegated to.
	Delegate string `protobuf:"bytes,3,opt,name=delegate,proto3" json:"delegate,omitempty"`
	// Account ID that capability grants access to.
	// This is the same as issuer when it's a first-grade capability,
	// but issuer can be different if the capability is delegated further down.
	Account string `protobuf:"bytes,4,opt,name=account,proto3" json:"account,omitempty"`
	// Path within the account which the capability grants access to.
	Path string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	// Role that the capability grants to the delegate.
	Role Role `protobuf:"varint,6,opt,name=role,proto3,enum=com.seed.documents.v3alpha.Role" json:"role,omitempty"`
	// Normally capabilities are applied recursively (i.e. path + all the subpaths),
	// but it can be limited to only to the exact path match.
	IsExact bool `protobuf:"varint,7,opt,name=is_exact,json=isExact,proto3" json:"is_exact,omitempty"`
	// Timestamp when this capability was issued.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Optional. Short, user-provided label for the capability for user's convenience to identify different capabilities.
	Label         string `protobuf:"bytes,9,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_access_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_access_control_proto_rawDescGZIP(), []int{5}
}

func (x *Capability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Capability) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Capability) GetDelegate() string {
	if x != nil {
		return x.Delegate
	}
	return ""
}

func (x *Capability) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Capability) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Capability) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Capability) GetIsExact() bool {
	if x != nil {
		return x.IsExact
	}
	return false
}

func (x *Capability) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Capability) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_documents_v3alpha_access_control_proto protoreflect.FileDescriptor

const file_documents_v3alpha_access_control_proto_rawDesc = "" +
	"\n" +
	"&documents/v3alpha/access_control.proto\x12\x1acom.seed.documents.v3alpha\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x01\n" +
	"\x17ListCapabilitiesRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12)\n" +
	"\x10ignore_inherited\x18\x03 \x01(\bR\x0fignoreInherited\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x8e\x01\n" +
	"\x18ListCapabilitiesResponse\x12J\n" +
	"\fcapabilities\x18\x01 \x03(\v2&.com.seed.documents.v3alpha.CapabilityR\fcapabilities\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"|\n" +
	"\"ListCapabilitiesForDelegateRequest\x12\x1a\n" +
	"\bdelegate\x18\x01 \x01(\tR\bdelegate\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\xfc\x01\n" +
	"\x17CreateCapabilityRequest\x12(\n" +
	"\x10signing_key_name\x18\x01 \x01(\tR\x0esigningKeyName\x12\x1a\n" +
	"\bdelegate\x18\x02 \x01(\tR\bdelegate\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x124\n" +
	"\x04role\x18\x05 \x01(\x0e2 .com.seed.documents.v3alpha.RoleR\x04role\x12!\n" +
	"\fno_recursive\x18\x06 \x01(\bR\vnoRecursive\x12\x14\n" +
	"\x05label\x18\a \x01(\tR\x05label\"&\n" +
	"\x14GetCapabilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa2\x02\n" +
	"\n" +
	"Capability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\bdelegate\x18\x03 \x01(\tR\bdelegate\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\tR\aaccount\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x124\n" +
	"\x04role\x18\x06 \x01(\x0e2 .com.seed.documents.v3alpha.RoleR\x04role\x12\x19\n" +
	"\bis_exact\x18\a \x01(\bR\aisExact\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12\x14\n" +
	"\x05label\x18\t \x01(\tR\x05label*3\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06WRITER\x10\x02\x12\t\n" +
	"\x05AGENT\x10\x032\x80\x04\n" +
	"\rAccessControl\x12}\n" +
	"\x10ListCapabilities\x123.com.seed.documents.v3alpha.ListCapabilitiesRequest\x1a4.com.seed.documents.v3alpha.ListCapabilitiesResponse\x12\x93\x01\n" +
	"\x1bListCapabilitiesForDelegate\x12>.com.seed.documents.v3alpha.ListCapabilitiesForDelegateRequest\x1a4.com.seed.documents.v3alpha.ListCapabilitiesResponse\x12o\n" +
	"\x10CreateCapability\x123.com.seed.documents.v3alpha.CreateCapabilityRequest\x1a&.com.seed.documents.v3alpha.Capability\x12i\n" +
	"\rGetCapability\x120.com.seed.documents.v3alpha.GetCapabilityRequest\x1a&.com.seed.documents.v3alpha.CapabilityB3Z1seed/backend/genproto/documents/v3alpha;documentsb\x06proto3"

var (
	file_documents_v3alpha_access_control_proto_rawDescOnce sync.Once
	file_documents_v3alpha_access_control_proto_rawDescData []byte
)

func file_documents_v3alpha_access_control_proto_rawDescGZIP() []byte {
	file_documents_v3alpha_access_control_proto_rawDescOnce.Do(func() {
		file_documents_v3alpha_access_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_documents_v3alpha_access_control_proto_rawDesc), len(file_documents_v3alpha_access_control_proto_rawDesc)))
	})
	return file_documents_v3alpha_access_control_proto_rawDescData
}

var file_documents_v3alpha_access_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_documents_v3alpha_access_control_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_documents_v3alpha_access_control_proto_goTypes = []any{
	(Role)(0),                                  // 0: com.seed.documents.v3alpha.Role
	(*ListCapabilitiesRequest)(nil),            // 1: com.seed.documents.v3alpha.ListCapabilitiesRequest
	(*ListCapabilitiesResponse)(nil),           // 2: com.seed.documents.v3alpha.ListCapabilitiesResponse
	(*ListCapabilitiesForDelegateRequest)(nil), // 3: com.seed.documents.v3alpha.ListCapabilitiesForDelegateRequest
	(*CreateCapabilityRequest)(nil),            // 4: com.seed.documents.v3alpha.CreateCapabilityRequest
	(*GetCapabilityRequest)(nil),               // 5: com.seed.documents.v3alpha.GetCapabilityRequest
	(*Capability)(nil),                         // 6: com.seed.documents.v3alpha.Capability
	(*timestamppb.Timestamp)(nil),              // 7: google.protobuf.Timestamp
}
var file_documents_v3alpha_access_control_proto_depIdxs = []int32{
	6, // 0: com.seed.documents.v3alpha.ListCapabilitiesResponse.capabilities:type_name -> com.seed.documents.v3alpha.Capability
	0, // 1: com.seed.documents.v3alpha.CreateCapabilityRequest.role:type_name -> com.seed.documents.v3alpha.Role
	0, // 2: com.seed.documents.v3alpha.Capability.role:type_name -> com.seed.documents.v3alpha.Role
	7, // 3: com.seed.documents.v3alpha.Capability.create_time:type_name -> google.protobuf.Timestamp
	1, // 4: com.seed.documents.v3alpha.AccessControl.ListCapabilities:input_type -> com.seed.documents.v3alpha.ListCapabilitiesRequest
	3, // 5: com.seed.documents.v3alpha.AccessControl.ListCapabilitiesForDelegate:input_type -> com.seed.documents.v3alpha.ListCapabilitiesForDelegateRequest
	4, // 6: com.seed.documents.v3alpha.AccessControl.CreateCapability:input_type -> com.seed.documents.v3alpha.CreateCapabilityRequest
	5, // 7: com.seed.documents.v3alpha.AccessControl.GetCapability:input_type -> com.seed.documents.v3alpha.GetCapabilityRequest
	2, // 8: com.seed.documents.v3alpha.AccessControl.ListCapabilities:output_type -> com.seed.documents.v3alpha.ListCapabilitiesResponse
	2, // 9: com.seed.documents.v3alpha.AccessControl.ListCapabilitiesForDelegate:output_type -> com.seed.documents.v3alpha.ListCapabilitiesResponse
	6, // 10: com.seed.documents.v3alpha.AccessControl.CreateCapability:output_type -> com.seed.documents.v3alpha.Capability
	6, // 11: com.seed.documents.v3alpha.AccessControl.GetCapability:output_type -> com.seed.documents.v3alpha.Capability
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_documents_v3alpha_access_control_proto_init() }
func file_documents_v3alpha_access_control_proto_init() {
	if File_documents_v3alpha_access_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_documents_v3alpha_access_control_proto_rawDesc), len(file_documents_v3alpha_access_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_documents_v3alpha_access_control_proto_goTypes,
		DependencyIndexes: file_documents_v3alpha_access_control_proto_depIdxs,
		EnumInfos:         file_documents_v3alpha_access_control_proto_enumTypes,
		MessageInfos:      file_documents_v3alpha_access_control_proto_msgTypes,
	}.Build()
	File_documents_v3alpha_access_control_proto = out.File
	file_documents_v3alpha_access_control_proto_goTypes = nil
	file_documents_v3alpha_access_control_proto_depIdxs = nil
}
