// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: documents/v3alpha/resources.proto

package documents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	v1alpha "seed/backend/genproto/p2p/v1alpha"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes the state of the discovery task.
type DiscoveryTaskState int32

const (
	// The task has just started.
	DiscoveryTaskState_DISCOVERY_TASK_STARTED DiscoveryTaskState = 0
	// The task is in progess — we keep looking for peers who can provide the content,
	// and downloading the content we are finding.
	DiscoveryTaskState_DISCOVERY_TASK_IN_PROGRESS DiscoveryTaskState = 1
	// The task has completed and the result is cached for the duration of the duration of the TTL.
	DiscoveryTaskState_DISCOVERY_TASK_COMPLETED DiscoveryTaskState = 2
)

// Enum value maps for DiscoveryTaskState.
var (
	DiscoveryTaskState_name = map[int32]string{
		0: "DISCOVERY_TASK_STARTED",
		1: "DISCOVERY_TASK_IN_PROGRESS",
		2: "DISCOVERY_TASK_COMPLETED",
	}
	DiscoveryTaskState_value = map[string]int32{
		"DISCOVERY_TASK_STARTED":     0,
		"DISCOVERY_TASK_IN_PROGRESS": 1,
		"DISCOVERY_TASK_COMPLETED":   2,
	}
)

func (x DiscoveryTaskState) Enum() *DiscoveryTaskState {
	p := new(DiscoveryTaskState)
	*p = x
	return p
}

func (x DiscoveryTaskState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryTaskState) Descriptor() protoreflect.EnumDescriptor {
	return file_documents_v3alpha_resources_proto_enumTypes[0].Descriptor()
}

func (DiscoveryTaskState) Type() protoreflect.EnumType {
	return &file_documents_v3alpha_resources_proto_enumTypes[0]
}

func (x DiscoveryTaskState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryTaskState.Descriptor instead.
func (DiscoveryTaskState) EnumDescriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{0}
}

// Describes the state of the discovery task.
type SearchType int32

const (
	// Keyword-based search.
	SearchType_SEARCH_KEYWORD SearchType = 0
	// Semantic search.
	SearchType_SEARCH_SEMANTIC SearchType = 1
	// Hybrid search. with RRFusion.
	SearchType_SEARCH_HYBRID SearchType = 2
)

// Enum value maps for SearchType.
var (
	SearchType_name = map[int32]string{
		0: "SEARCH_KEYWORD",
		1: "SEARCH_SEMANTIC",
		2: "SEARCH_HYBRID",
	}
	SearchType_value = map[string]int32{
		"SEARCH_KEYWORD":  0,
		"SEARCH_SEMANTIC": 1,
		"SEARCH_HYBRID":   2,
	}
)

func (x SearchType) Enum() *SearchType {
	p := new(SearchType)
	*p = x
	return p
}

func (x SearchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchType) Descriptor() protoreflect.EnumDescriptor {
	return file_documents_v3alpha_resources_proto_enumTypes[1].Descriptor()
}

func (SearchType) Type() protoreflect.EnumType {
	return &file_documents_v3alpha_resources_proto_enumTypes[1]
}

func (x SearchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchType.Descriptor instead.
func (SearchType) EnumDescriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{1}
}

// Content type to filter search results by.
type ContentTypeFilter int32

const (
	ContentTypeFilter_CONTENT_TYPE_TITLE    ContentTypeFilter = 0
	ContentTypeFilter_CONTENT_TYPE_DOCUMENT ContentTypeFilter = 1
	ContentTypeFilter_CONTENT_TYPE_COMMENT  ContentTypeFilter = 2
	ContentTypeFilter_CONTENT_TYPE_CONTACT  ContentTypeFilter = 3
)

// Enum value maps for ContentTypeFilter.
var (
	ContentTypeFilter_name = map[int32]string{
		0: "CONTENT_TYPE_TITLE",
		1: "CONTENT_TYPE_DOCUMENT",
		2: "CONTENT_TYPE_COMMENT",
		3: "CONTENT_TYPE_CONTACT",
	}
	ContentTypeFilter_value = map[string]int32{
		"CONTENT_TYPE_TITLE":    0,
		"CONTENT_TYPE_DOCUMENT": 1,
		"CONTENT_TYPE_COMMENT":  2,
		"CONTENT_TYPE_CONTACT":  3,
	}
)

func (x ContentTypeFilter) Enum() *ContentTypeFilter {
	p := new(ContentTypeFilter)
	*p = x
	return p
}

func (x ContentTypeFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentTypeFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_documents_v3alpha_resources_proto_enumTypes[2].Descriptor()
}

func (ContentTypeFilter) Type() protoreflect.EnumType {
	return &file_documents_v3alpha_resources_proto_enumTypes[2]
}

func (x ContentTypeFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentTypeFilter.Descriptor instead.
func (ContentTypeFilter) EnumDescriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{2}
}

// Request to get a single resource by its IRI.
type GetResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. IRI of the resource to retrieve.
	Iri           string `protobuf:"bytes,1,opt,name=iri,proto3" json:"iri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{0}
}

func (x *GetResourceRequest) GetIri() string {
	if x != nil {
		return x.Iri
	}
	return ""
}

// An identifiable entity, accessible with a unique identifier.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Various kinds of resources.
	//
	// Types that are valid to be assigned to Kind:
	//
	//	*Resource_Document
	//	*Resource_Comment
	//	*Resource_Contact
	Kind isResource_Kind `protobuf_oneof:"kind"`
	// Optional. The version of the resource (when applicable).
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{1}
}

func (x *Resource) GetKind() isResource_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Resource) GetDocument() *Document {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *Resource) GetComment() *Comment {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Comment); ok {
			return x.Comment
		}
	}
	return nil
}

func (x *Resource) GetContact() *Contact {
	if x != nil {
		if x, ok := x.Kind.(*Resource_Contact); ok {
			return x.Contact
		}
	}
	return nil
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type isResource_Kind interface {
	isResource_Kind()
}

type Resource_Document struct {
	Document *Document `protobuf:"bytes,1,opt,name=document,proto3,oneof"`
}

type Resource_Comment struct {
	Comment *Comment `protobuf:"bytes,2,opt,name=comment,proto3,oneof"`
}

type Resource_Contact struct {
	Contact *Contact `protobuf:"bytes,3,opt,name=contact,proto3,oneof"`
}

func (*Resource_Document) isResource_Kind() {}

func (*Resource_Comment) isResource_Kind() {}

func (*Resource_Contact) isResource_Kind() {}

type PushResourcesToPeerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of multiaddrs for the same peer ID to attempt p2p connection.
	// For example `/ip4/10.0.0.1/tcp/55000/p2p/QmDeadBeef`.
	Addrs []string `protobuf:"bytes,1,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// Required. Resource IRIs to push. We will also push
	// related blobs to those resources. No wilcards are supported.
	// Only documents resources can be specified. No single comments supported yet.
	// See https://seedteamtalks.hyper.media/projects/daemon-pushing-algo
	Resources []string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	// Optional. Whether to push children documents recursively as well.
	Recursive     bool `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushResourcesToPeerRequest) Reset() {
	*x = PushResourcesToPeerRequest{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResourcesToPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResourcesToPeerRequest) ProtoMessage() {}

func (x *PushResourcesToPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResourcesToPeerRequest.ProtoReflect.Descriptor instead.
func (*PushResourcesToPeerRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{2}
}

func (x *PushResourcesToPeerRequest) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *PushResourcesToPeerRequest) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *PushResourcesToPeerRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// Request to list citations of a resource.
type ListCitationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. IRI of the cited resource.
	Iri string `protobuf:"bytes,1,opt,name=iri,proto3" json:"iri,omitempty"`
	// Optional. The size of the page to return by the server.
	// The server may ignore this, and return a bigger response.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. The page token to continue the pagination.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Optional. Whether to return the results in descending order (newest-first).
	// By default citations are listed in the chronological order,
	// according to the *locally perceived* order of the blobs that contain the citations.
	//
	// I.e. we sort the links according to the time we receive the blobs, not according to the time blobs claim to have been created.
	// This is to prevent losing new citations in case of receiving out-of-date blobs.
	//
	// This flag must remain the same when paginating through the results.
	ReverseOrder  bool `protobuf:"varint,4,opt,name=reverse_order,json=reverseOrder,proto3" json:"reverse_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitationsRequest) Reset() {
	*x = ListCitationsRequest{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitationsRequest) ProtoMessage() {}

func (x *ListCitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitationsRequest.ProtoReflect.Descriptor instead.
func (*ListCitationsRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{3}
}

func (x *ListCitationsRequest) GetIri() string {
	if x != nil {
		return x.Iri
	}
	return ""
}

func (x *ListCitationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCitationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCitationsRequest) GetReverseOrder() bool {
	if x != nil {
		return x.ReverseOrder
	}
	return false
}

// Response to list citations of a resource.
type ListCitationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The list of citations for the resource.
	Citations []*Citation `protobuf:"bytes,1,rep,name=citations,proto3" json:"citations,omitempty"`
	// Optional. Token for the next page if there's any.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCitationsResponse) Reset() {
	*x = ListCitationsResponse{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCitationsResponse) ProtoMessage() {}

func (x *ListCitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCitationsResponse.ProtoReflect.Descriptor instead.
func (*ListCitationsResponse) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{4}
}

func (x *ListCitationsResponse) GetCitations() []*Citation {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *ListCitationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Citation of a resource.
// Source means the place where the citation was found.
// Target means the resource being cited.
type Citation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The source blob where the citation was found.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Required. The type of the source where the citation was found.
	SourceType string `protobuf:"bytes,2,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	// Required. Context can mean different things depending on the type of the source:
	// it can be the block ID when source type is a Document or Comment.
	SourceContext string `protobuf:"bytes,3,opt,name=source_context,json=sourceContext,proto3" json:"source_context,omitempty"`
	// Required. Information about the blob where the citation was found.
	SourceBlob *Citation_BlobInfo `protobuf:"bytes,4,opt,name=source_blob,json=sourceBlob,proto3" json:"source_blob,omitempty"`
	// Required. Specifies whether the link points to the exact/pinned version of the target document,
	// or if the target version is a *suggested* minimum version, and a later one should be preferred if exists.
	IsExactVersion bool `protobuf:"varint,5,opt,name=is_exact_version,json=isExactVersion,proto3" json:"is_exact_version,omitempty"`
	// Optional. Specifies the document where the citation was found. Relevant for comments.
	SourceDocument string `protobuf:"bytes,6,opt,name=source_document,json=sourceDocument,proto3" json:"source_document,omitempty"`
	// Optional. The target resource the link points to.
	Target string `protobuf:"bytes,10,opt,name=target,proto3" json:"target,omitempty"`
	// Optional. The version of the target resource the link points to.
	TargetVersion string `protobuf:"bytes,7,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	// Optional. The fragment portion of the link.
	TargetFragment string `protobuf:"bytes,8,opt,name=target_fragment,json=targetFragment,proto3" json:"target_fragment,omitempty"`
	// Optional. The revision of the target block at target_version, when target_fragment
	// points to a block or text range.
	TargetBlockRevision string `protobuf:"bytes,11,opt,name=target_block_revision,json=targetBlockRevision,proto3" json:"target_block_revision,omitempty"`
	// Optional. The type of citation. Could be embed, link, ...
	CitationType  string `protobuf:"bytes,9,opt,name=citation_type,json=citationType,proto3" json:"citation_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation) Reset() {
	*x = Citation{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation) ProtoMessage() {}

func (x *Citation) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation.ProtoReflect.Descriptor instead.
func (*Citation) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{5}
}

func (x *Citation) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Citation) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Citation) GetSourceContext() string {
	if x != nil {
		return x.SourceContext
	}
	return ""
}

func (x *Citation) GetSourceBlob() *Citation_BlobInfo {
	if x != nil {
		return x.SourceBlob
	}
	return nil
}

func (x *Citation) GetIsExactVersion() bool {
	if x != nil {
		return x.IsExactVersion
	}
	return false
}

func (x *Citation) GetSourceDocument() string {
	if x != nil {
		return x.SourceDocument
	}
	return ""
}

func (x *Citation) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Citation) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *Citation) GetTargetFragment() string {
	if x != nil {
		return x.TargetFragment
	}
	return ""
}

func (x *Citation) GetTargetBlockRevision() string {
	if x != nil {
		return x.TargetBlockRevision
	}
	return ""
}

func (x *Citation) GetCitationType() string {
	if x != nil {
		return x.CitationType
	}
	return ""
}

// Request to discover a resource.
//
// The discovery target is specified EITHER by `id` (preferred — single hm:// URL,
// suitable as a dedup key for clients that aggregate concurrent discovery requests)
// OR by the decomposed `account` + `path` pair (with optional `recursive`).
// Setting both forms in the same request is an error.
type DiscoverResourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hm:// URL identifying the discovery target. Mutually exclusive with
	// `account` + `path` + `recursive`.
	//
	// Examples — exact path:
	//
	//	"hm://ACCOUNT_ID"                   — everything at account root
	//	"hm://ACCOUNT_ID/notes/foo"         — everything at /notes/foo
	//
	// Examples — wildcards (must be the final path segment):
	//
	//	"hm://ACCOUNT_ID/notes/*"           — direct children of /notes only
	//	"hm://ACCOUNT_ID/notes/**"          — /notes and everything under it
	//	"hm://ACCOUNT_ID/**"                — entire account
	//
	// Examples — scope keyword (suffix on the last path segment):
	//
	//	"hm://ACCOUNT_ID/:profile"          — profile blobs at account root
	//	"hm://ACCOUNT_ID/notes/foo:profile" — profile blobs at /notes/foo
	//
	// Wildcards and scope keywords are mutually exclusive in a single URL.
	// Reserved (not yet implemented): "/path:directory".
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// The account the resource belongs to. Mutually exclusive with `id`.
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The path of the wanted resource. Mutually exclusive with `id`.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// Optional. Version of the resource to discover.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Optional. If true, we sync the document and the child documents as well.
	// Mutually exclusive with `id` — when using `id`, encode recursion via the
	// `**` suffix instead. Prefer the `id` form for new callers.
	Recursive     bool `protobuf:"varint,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResourceRequest) Reset() {
	*x = DiscoverResourceRequest{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResourceRequest) ProtoMessage() {}

func (x *DiscoverResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResourceRequest.ProtoReflect.Descriptor instead.
func (*DiscoverResourceRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoverResourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiscoverResourceRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DiscoverResourceRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiscoverResourceRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiscoverResourceRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// Response to discover a resource.
type DiscoverResourceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The cached version of the document we've discovered within the last discovery process.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// The state of the discovery task.
	State DiscoveryTaskState `protobuf:"varint,2,opt,name=state,proto3,enum=com.seed.documents.v3alpha.DiscoveryTaskState" json:"state,omitempty"`
	// The timestamp of the last result we've found.
	// It can be empty if the discovery is still in progress.
	LastResultTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_result_time,json=lastResultTime,proto3" json:"last_result_time,omitempty"`
	// The cached error message of the last discovery attempt if it failed.
	LastError string `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// The time when the currently cached result will expire, and a new discovery attempt will be made,
	// if the client keeps calling the discovery RPC.
	// Can be empty if no results have been found yet.
	ResultExpireTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=result_expire_time,json=resultExpireTime,proto3" json:"result_expire_time,omitempty"`
	// The progress of the discovery process.
	Progress      *DiscoveryProgress `protobuf:"bytes,7,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResourceResponse) Reset() {
	*x = DiscoverResourceResponse{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResourceResponse) ProtoMessage() {}

func (x *DiscoverResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResourceResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResourceResponse) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{7}
}

func (x *DiscoverResourceResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiscoverResourceResponse) GetState() DiscoveryTaskState {
	if x != nil {
		return x.State
	}
	return DiscoveryTaskState_DISCOVERY_TASK_STARTED
}

func (x *DiscoverResourceResponse) GetLastResultTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastResultTime
	}
	return nil
}

func (x *DiscoverResourceResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *DiscoverResourceResponse) GetResultExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ResultExpireTime
	}
	return nil
}

func (x *DiscoverResourceResponse) GetProgress() *DiscoveryProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

// Various metrics reporting on the progress of the discovery process.
type DiscoveryProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of peers we have found so far.
	PeersFound int32 `protobuf:"varint,1,opt,name=peers_found,json=peersFound,proto3" json:"peers_found,omitempty"`
	// Number of peers we have successfully synced with.
	PeersSyncedOk int32 `protobuf:"varint,2,opt,name=peers_synced_ok,json=peersSyncedOk,proto3" json:"peers_synced_ok,omitempty"`
	// Number of peers we have failed to sync with.
	PeersFailed int32 `protobuf:"varint,3,opt,name=peers_failed,json=peersFailed,proto3" json:"peers_failed,omitempty"`
	// Number of blobs we have discovered so far.
	BlobsDiscovered int32 `protobuf:"varint,4,opt,name=blobs_discovered,json=blobsDiscovered,proto3" json:"blobs_discovered,omitempty"`
	// Number of blobs we have successfully downloaded.
	BlobsDownloaded int32 `protobuf:"varint,5,opt,name=blobs_downloaded,json=blobsDownloaded,proto3" json:"blobs_downloaded,omitempty"`
	// Number of blobs we have failed to download.
	BlobsFailed   int32 `protobuf:"varint,6,opt,name=blobs_failed,json=blobsFailed,proto3" json:"blobs_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryProgress) Reset() {
	*x = DiscoveryProgress{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryProgress) ProtoMessage() {}

func (x *DiscoveryProgress) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryProgress.ProtoReflect.Descriptor instead.
func (*DiscoveryProgress) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoveryProgress) GetPeersFound() int32 {
	if x != nil {
		return x.PeersFound
	}
	return 0
}

func (x *DiscoveryProgress) GetPeersSyncedOk() int32 {
	if x != nil {
		return x.PeersSyncedOk
	}
	return 0
}

func (x *DiscoveryProgress) GetPeersFailed() int32 {
	if x != nil {
		return x.PeersFailed
	}
	return 0
}

func (x *DiscoveryProgress) GetBlobsDiscovered() int32 {
	if x != nil {
		return x.BlobsDiscovered
	}
	return 0
}

func (x *DiscoveryProgress) GetBlobsDownloaded() int32 {
	if x != nil {
		return x.BlobsDownloaded
	}
	return 0
}

func (x *DiscoveryProgress) GetBlobsFailed() int32 {
	if x != nil {
		return x.BlobsFailed
	}
	return 0
}

// A resource record found
type ResourceSearchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IRI of the resource, including version, block id and range
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Blob Id of the resource containing the matching record.
	BlobId string `protobuf:"bytes,2,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	// The time of the version of the resource.
	VersionTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=version_time,json=versionTime,proto3" json:"version_time,omitempty"`
	// In the case of comments, the document id
	// containing the comment.
	DocId string `protobuf:"bytes,4,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	// Content of the resource, depending on the type:
	// Alias in the case of account.
	// Title/Body in the case of groups and documents.
	// Body in the case of comments. We don't fill up the whole
	// block, just the part that contains the search term, with
	// the surrounding context. The context size is defined by
	// the context_size parameter.
	Content string `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	// The owner of the resource
	Owner string `protobuf:"bytes,6,opt,name=owner,proto3" json:"owner,omitempty"`
	// The type of the resource it coud be Title, Document, Comment, ...
	Type string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	// Icon of the document containing that resource
	Icon string `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	// Parent document names
	ParentNames []string `protobuf:"bytes,9,rep,name=parent_names,json=parentNames,proto3" json:"parent_names,omitempty"`
	// Metadata of the document containing that resource.
	Metadata      string `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSearchResult) Reset() {
	*x = ResourceSearchResult{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSearchResult) ProtoMessage() {}

func (x *ResourceSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSearchResult.ProtoReflect.Descriptor instead.
func (*ResourceSearchResult) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceSearchResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResourceSearchResult) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *ResourceSearchResult) GetVersionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.VersionTime
	}
	return nil
}

func (x *ResourceSearchResult) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ResourceSearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ResourceSearchResult) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ResourceSearchResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceSearchResult) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ResourceSearchResult) GetParentNames() []string {
	if x != nil {
		return x.ParentNames
	}
	return nil
}

func (x *ResourceSearchResult) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// Request to search resources.
type SearchResourcesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query to find. We support wildcards and phrases.
	// See https://sqlite.org/fts5.html#full_text_query_syntax.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Deprecated, use content_type_filters instead to specify
	// which content types to include in the search.
	//
	// Deprecated: Marked as deprecated in documents/v3alpha/resources.proto.
	IncludeBody bool `protobuf:"varint,2,opt,name=include_body,json=includeBody,proto3" json:"include_body,omitempty"`
	// Optional. The size of the text accompanying the search match.
	// Half of the size is before the match, and half after.
	// Default is 48 runes.
	ContextSize int32 `protobuf:"varint,3,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	// Deprecated. Use iri_filter instead.
	//
	// Deprecated: Marked as deprecated in documents/v3alpha/resources.proto.
	AccountUid string `protobuf:"bytes,4,opt,name=account_uid,json=accountUid,proto3" json:"account_uid,omitempty"`
	// Optional. The account uid the user is logged in with.
	// This is used to filter out contacts that the user doesn't have access to.
	// If not set, we won't provide any contact resources in the response.
	LoggedAccountUid string `protobuf:"bytes,5,opt,name=logged_account_uid,json=loggedAccountUid,proto3" json:"logged_account_uid,omitempty"`
	// Optional. Type of search to perform. Could be keyword, semantic or hybrid.
	// if not set, keyword search is used.
	SearchType SearchType `protobuf:"varint,6,opt,name=search_type,json=searchType,proto3,enum=com.seed.documents.v3alpha.SearchType" json:"search_type,omitempty"`
	// Optional. hm:// URL with optional GLOB wildcards to scope search.
	// Examples: "hm://<account>/cars/honda" (single doc), "hm://<account>/cars/*" (subtree).
	// When empty, falls back to account_uid if set, otherwise matches all.
	IriFilter string `protobuf:"bytes,7,opt,name=iri_filter,json=iriFilter,proto3" json:"iri_filter,omitempty"`
	// Optional. Fine-grained content type selection. Overrides include_body when set.
	// When empty, legacy behavior (title + body types based on include_body).
	ContentTypeFilter []ContentTypeFilter `protobuf:"varint,8,rep,packed,name=content_type_filter,json=contentTypeFilter,proto3,enum=com.seed.documents.v3alpha.ContentTypeFilter" json:"content_type_filter,omitempty"`
	// Optional. Authority weight for citation-based ranking. Range [0, 1].
	// 0 (default) disables authority scoring. Higher values increase citation influence.
	// Final score: (1-weight)*textRRF + 0.7*weight*docAuthRRF + 0.3*weight*authorAuthRRF.
	AuthorityWeight float32 `protobuf:"fixed32,9,opt,name=authority_weight,json=authorityWeight,proto3" json:"authority_weight,omitempty"`
	// Optional. Maximum number of results per page.
	// When 0 (default), all results are returned (backwards compatible).
	PageSize int32 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Optional. Token from a previous SearchResourcesResponse to get the next page.
	PageToken     string `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourcesRequest) Reset() {
	*x = SearchResourcesRequest{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourcesRequest) ProtoMessage() {}

func (x *SearchResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourcesRequest.ProtoReflect.Descriptor instead.
func (*SearchResourcesRequest) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{10}
}

func (x *SearchResourcesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// Deprecated: Marked as deprecated in documents/v3alpha/resources.proto.
func (x *SearchResourcesRequest) GetIncludeBody() bool {
	if x != nil {
		return x.IncludeBody
	}
	return false
}

func (x *SearchResourcesRequest) GetContextSize() int32 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

// Deprecated: Marked as deprecated in documents/v3alpha/resources.proto.
func (x *SearchResourcesRequest) GetAccountUid() string {
	if x != nil {
		return x.AccountUid
	}
	return ""
}

func (x *SearchResourcesRequest) GetLoggedAccountUid() string {
	if x != nil {
		return x.LoggedAccountUid
	}
	return ""
}

func (x *SearchResourcesRequest) GetSearchType() SearchType {
	if x != nil {
		return x.SearchType
	}
	return SearchType_SEARCH_KEYWORD
}

func (x *SearchResourcesRequest) GetIriFilter() string {
	if x != nil {
		return x.IriFilter
	}
	return ""
}

func (x *SearchResourcesRequest) GetContentTypeFilter() []ContentTypeFilter {
	if x != nil {
		return x.ContentTypeFilter
	}
	return nil
}

func (x *SearchResourcesRequest) GetAuthorityWeight() float32 {
	if x != nil {
		return x.AuthorityWeight
	}
	return 0
}

func (x *SearchResourcesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchResourcesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// A list of resources matching the request.
type SearchResourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resources matching the input title
	Resources []*ResourceSearchResult `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	// Token for the next page if there's any.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResourcesResponse) Reset() {
	*x = SearchResourcesResponse{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResourcesResponse) ProtoMessage() {}

func (x *SearchResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResourcesResponse.ProtoReflect.Descriptor instead.
func (*SearchResourcesResponse) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{11}
}

func (x *SearchResourcesResponse) GetResources() []*ResourceSearchResult {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SearchResourcesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Information about a structural blob that contains the citation.
type Citation_BlobInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The CID-formatted hash of the blob.
	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// The Account ID of the author of the blob.
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// The timestamp of the blob.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Citation_BlobInfo) Reset() {
	*x = Citation_BlobInfo{}
	mi := &file_documents_v3alpha_resources_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Citation_BlobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Citation_BlobInfo) ProtoMessage() {}

func (x *Citation_BlobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_documents_v3alpha_resources_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Citation_BlobInfo.ProtoReflect.Descriptor instead.
func (*Citation_BlobInfo) Descriptor() ([]byte, []int) {
	return file_documents_v3alpha_resources_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Citation_BlobInfo) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Citation_BlobInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Citation_BlobInfo) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

var File_documents_v3alpha_resources_proto protoreflect.FileDescriptor

const file_documents_v3alpha_resources_proto_rawDesc = "" +
	"\n" +
	"!documents/v3alpha/resources.proto\x12\x1acom.seed.documents.v3alpha\x1a!documents/v3alpha/documents.proto\x1a documents/v3alpha/comments.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19p2p/v1alpha/syncing.proto\"&\n" +
	"\x12GetResourceRequest\x12\x10\n" +
	"\x03iri\x18\x01 \x01(\tR\x03iri\"\xf2\x01\n" +
	"\bResource\x12B\n" +
	"\bdocument\x18\x01 \x01(\v2$.com.seed.documents.v3alpha.DocumentH\x00R\bdocument\x12?\n" +
	"\acomment\x18\x02 \x01(\v2#.com.seed.documents.v3alpha.CommentH\x00R\acomment\x12?\n" +
	"\acontact\x18\x03 \x01(\v2#.com.seed.documents.v3alpha.ContactH\x00R\acontact\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversionB\x06\n" +
	"\x04kind\"n\n" +
	"\x1aPushResourcesToPeerRequest\x12\x14\n" +
	"\x05addrs\x18\x01 \x03(\tR\x05addrs\x12\x1c\n" +
	"\tresources\x18\x02 \x03(\tR\tresources\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\"\x89\x01\n" +
	"\x14ListCitationsRequest\x12\x10\n" +
	"\x03iri\x18\x01 \x01(\tR\x03iri\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12#\n" +
	"\rreverse_order\x18\x04 \x01(\bR\freverseOrder\"\x83\x01\n" +
	"\x15ListCitationsResponse\x12B\n" +
	"\tcitations\x18\x01 \x03(\v2$.com.seed.documents.v3alpha.CitationR\tcitations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc1\x04\n" +
	"\bCitation\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1f\n" +
	"\vsource_type\x18\x02 \x01(\tR\n" +
	"sourceType\x12%\n" +
	"\x0esource_context\x18\x03 \x01(\tR\rsourceContext\x12N\n" +
	"\vsource_blob\x18\x04 \x01(\v2-.com.seed.documents.v3alpha.Citation.BlobInfoR\n" +
	"sourceBlob\x12(\n" +
	"\x10is_exact_version\x18\x05 \x01(\bR\x0eisExactVersion\x12'\n" +
	"\x0fsource_document\x18\x06 \x01(\tR\x0esourceDocument\x12\x16\n" +
	"\x06target\x18\n" +
	" \x01(\tR\x06target\x12%\n" +
	"\x0etarget_version\x18\a \x01(\tR\rtargetVersion\x12'\n" +
	"\x0ftarget_fragment\x18\b \x01(\tR\x0etargetFragment\x122\n" +
	"\x15target_block_revision\x18\v \x01(\tR\x13targetBlockRevision\x12#\n" +
	"\rcitation_type\x18\t \x01(\tR\fcitationType\x1aq\n" +
	"\bBlobInfo\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\x8f\x01\n" +
	"\x17DiscoverResourceRequest\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\trecursive\x18\x04 \x01(\bR\trecursive\"\xfa\x02\n" +
	"\x18DiscoverResourceResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12D\n" +
	"\x05state\x18\x02 \x01(\x0e2..com.seed.documents.v3alpha.DiscoveryTaskStateR\x05state\x12D\n" +
	"\x10last_result_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastResultTime\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x12H\n" +
	"\x12result_expire_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x10resultExpireTime\x12I\n" +
	"\bprogress\x18\a \x01(\v2-.com.seed.documents.v3alpha.DiscoveryProgressR\bprogressJ\x04\b\x03\x10\x04\"\xf8\x01\n" +
	"\x11DiscoveryProgress\x12\x1f\n" +
	"\vpeers_found\x18\x01 \x01(\x05R\n" +
	"peersFound\x12&\n" +
	"\x0fpeers_synced_ok\x18\x02 \x01(\x05R\rpeersSyncedOk\x12!\n" +
	"\fpeers_failed\x18\x03 \x01(\x05R\vpeersFailed\x12)\n" +
	"\x10blobs_discovered\x18\x04 \x01(\x05R\x0fblobsDiscovered\x12)\n" +
	"\x10blobs_downloaded\x18\x05 \x01(\x05R\x0fblobsDownloaded\x12!\n" +
	"\fblobs_failed\x18\x06 \x01(\x05R\vblobsFailed\"\xac\x02\n" +
	"\x14ResourceSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ablob_id\x18\x02 \x01(\tR\x06blobId\x12=\n" +
	"\fversion_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vversionTime\x12\x15\n" +
	"\x06doc_id\x18\x04 \x01(\tR\x05docId\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x14\n" +
	"\x05owner\x18\x06 \x01(\tR\x05owner\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12!\n" +
	"\fparent_names\x18\t \x03(\tR\vparentNames\x12\x1a\n" +
	"\bmetadata\x18\n" +
	" \x01(\tR\bmetadata\"\xf9\x03\n" +
	"\x16SearchResourcesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\finclude_body\x18\x02 \x01(\bB\x02\x18\x01R\vincludeBody\x12!\n" +
	"\fcontext_size\x18\x03 \x01(\x05R\vcontextSize\x12#\n" +
	"\vaccount_uid\x18\x04 \x01(\tB\x02\x18\x01R\n" +
	"accountUid\x12,\n" +
	"\x12logged_account_uid\x18\x05 \x01(\tR\x10loggedAccountUid\x12G\n" +
	"\vsearch_type\x18\x06 \x01(\x0e2&.com.seed.documents.v3alpha.SearchTypeR\n" +
	"searchType\x12\x1d\n" +
	"\n" +
	"iri_filter\x18\a \x01(\tR\tiriFilter\x12]\n" +
	"\x13content_type_filter\x18\b \x03(\x0e2-.com.seed.documents.v3alpha.ContentTypeFilterR\x11contentTypeFilter\x12)\n" +
	"\x10authority_weight\x18\t \x01(\x02R\x0fauthorityWeight\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"\x91\x01\n" +
	"\x17SearchResourcesResponse\x12N\n" +
	"\tresources\x18\x01 \x03(\v20.com.seed.documents.v3alpha.ResourceSearchResultR\tresources\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*n\n" +
	"\x12DiscoveryTaskState\x12\x1a\n" +
	"\x16DISCOVERY_TASK_STARTED\x10\x00\x12\x1e\n" +
	"\x1aDISCOVERY_TASK_IN_PROGRESS\x10\x01\x12\x1c\n" +
	"\x18DISCOVERY_TASK_COMPLETED\x10\x02*H\n" +
	"\n" +
	"SearchType\x12\x12\n" +
	"\x0eSEARCH_KEYWORD\x10\x00\x12\x13\n" +
	"\x0fSEARCH_SEMANTIC\x10\x01\x12\x11\n" +
	"\rSEARCH_HYBRID\x10\x02*z\n" +
	"\x11ContentTypeFilter\x12\x16\n" +
	"\x12CONTENT_TYPE_TITLE\x10\x00\x12\x19\n" +
	"\x15CONTENT_TYPE_DOCUMENT\x10\x01\x12\x18\n" +
	"\x14CONTENT_TYPE_COMMENT\x10\x02\x12\x18\n" +
	"\x14CONTENT_TYPE_CONTACT\x10\x032\xdf\x04\n" +
	"\tResources\x12c\n" +
	"\vGetResource\x12..com.seed.documents.v3alpha.GetResourceRequest\x1a$.com.seed.documents.v3alpha.Resource\x12}\n" +
	"\x10DiscoverResource\x123.com.seed.documents.v3alpha.DiscoverResourceRequest\x1a4.com.seed.documents.v3alpha.DiscoverResourceResponse\x12z\n" +
	"\x0fSearchResources\x122.com.seed.documents.v3alpha.SearchResourcesRequest\x1a3.com.seed.documents.v3alpha.SearchResourcesResponse\x12t\n" +
	"\rListCitations\x120.com.seed.documents.v3alpha.ListCitationsRequest\x1a1.com.seed.documents.v3alpha.ListCitationsResponse\x12|\n" +
	"\x13PushResourcesToPeer\x126.com.seed.documents.v3alpha.PushResourcesToPeerRequest\x1a+.com.seed.p2p.v1alpha.AnnounceBlobsProgress0\x01B3Z1seed/backend/genproto/documents/v3alpha;documentsb\x06proto3"

var (
	file_documents_v3alpha_resources_proto_rawDescOnce sync.Once
	file_documents_v3alpha_resources_proto_rawDescData []byte
)

func file_documents_v3alpha_resources_proto_rawDescGZIP() []byte {
	file_documents_v3alpha_resources_proto_rawDescOnce.Do(func() {
		file_documents_v3alpha_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_documents_v3alpha_resources_proto_rawDesc), len(file_documents_v3alpha_resources_proto_rawDesc)))
	})
	return file_documents_v3alpha_resources_proto_rawDescData
}

var file_documents_v3alpha_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_documents_v3alpha_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_documents_v3alpha_resources_proto_goTypes = []any{
	(DiscoveryTaskState)(0),               // 0: com.seed.documents.v3alpha.DiscoveryTaskState
	(SearchType)(0),                       // 1: com.seed.documents.v3alpha.SearchType
	(ContentTypeFilter)(0),                // 2: com.seed.documents.v3alpha.ContentTypeFilter
	(*GetResourceRequest)(nil),            // 3: com.seed.documents.v3alpha.GetResourceRequest
	(*Resource)(nil),                      // 4: com.seed.documents.v3alpha.Resource
	(*PushResourcesToPeerRequest)(nil),    // 5: com.seed.documents.v3alpha.PushResourcesToPeerRequest
	(*ListCitationsRequest)(nil),          // 6: com.seed.documents.v3alpha.ListCitationsRequest
	(*ListCitationsResponse)(nil),         // 7: com.seed.documents.v3alpha.ListCitationsResponse
	(*Citation)(nil),                      // 8: com.seed.documents.v3alpha.Citation
	(*DiscoverResourceRequest)(nil),       // 9: com.seed.documents.v3alpha.DiscoverResourceRequest
	(*DiscoverResourceResponse)(nil),      // 10: com.seed.documents.v3alpha.DiscoverResourceResponse
	(*DiscoveryProgress)(nil),             // 11: com.seed.documents.v3alpha.DiscoveryProgress
	(*ResourceSearchResult)(nil),          // 12: com.seed.documents.v3alpha.ResourceSearchResult
	(*SearchResourcesRequest)(nil),        // 13: com.seed.documents.v3alpha.SearchResourcesRequest
	(*SearchResourcesResponse)(nil),       // 14: com.seed.documents.v3alpha.SearchResourcesResponse
	(*Citation_BlobInfo)(nil),             // 15: com.seed.documents.v3alpha.Citation.BlobInfo
	(*Document)(nil),                      // 16: com.seed.documents.v3alpha.Document
	(*Comment)(nil),                       // 17: com.seed.documents.v3alpha.Comment
	(*Contact)(nil),                       // 18: com.seed.documents.v3alpha.Contact
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
	(*v1alpha.AnnounceBlobsProgress)(nil), // 20: com.seed.p2p.v1alpha.AnnounceBlobsProgress
}
var file_documents_v3alpha_resources_proto_depIdxs = []int32{
	16, // 0: com.seed.documents.v3alpha.Resource.document:type_name -> com.seed.documents.v3alpha.Document
	17, // 1: com.seed.documents.v3alpha.Resource.comment:type_name -> com.seed.documents.v3alpha.Comment
	18, // 2: com.seed.documents.v3alpha.Resource.contact:type_name -> com.seed.documents.v3alpha.Contact
	8,  // 3: com.seed.documents.v3alpha.ListCitationsResponse.citations:type_name -> com.seed.documents.v3alpha.Citation
	15, // 4: com.seed.documents.v3alpha.Citation.source_blob:type_name -> com.seed.documents.v3alpha.Citation.BlobInfo
	0,  // 5: com.seed.documents.v3alpha.DiscoverResourceResponse.state:type_name -> com.seed.documents.v3alpha.DiscoveryTaskState
	19, // 6: com.seed.documents.v3alpha.DiscoverResourceResponse.last_result_time:type_name -> google.protobuf.Timestamp
	19, // 7: com.seed.documents.v3alpha.DiscoverResourceResponse.result_expire_time:type_name -> google.protobuf.Timestamp
	11, // 8: com.seed.documents.v3alpha.DiscoverResourceResponse.progress:type_name -> com.seed.documents.v3alpha.DiscoveryProgress
	19, // 9: com.seed.documents.v3alpha.ResourceSearchResult.version_time:type_name -> google.protobuf.Timestamp
	1,  // 10: com.seed.documents.v3alpha.SearchResourcesRequest.search_type:type_name -> com.seed.documents.v3alpha.SearchType
	2,  // 11: com.seed.documents.v3alpha.SearchResourcesRequest.content_type_filter:type_name -> com.seed.documents.v3alpha.ContentTypeFilter
	12, // 12: com.seed.documents.v3alpha.SearchResourcesResponse.resources:type_name -> com.seed.documents.v3alpha.ResourceSearchResult
	19, // 13: com.seed.documents.v3alpha.Citation.BlobInfo.create_time:type_name -> google.protobuf.Timestamp
	3,  // 14: com.seed.documents.v3alpha.Resources.GetResource:input_type -> com.seed.documents.v3alpha.GetResourceRequest
	9,  // 15: com.seed.documents.v3alpha.Resources.DiscoverResource:input_type -> com.seed.documents.v3alpha.DiscoverResourceRequest
	13, // 16: com.seed.documents.v3alpha.Resources.SearchResources:input_type -> com.seed.documents.v3alpha.SearchResourcesRequest
	6,  // 17: com.seed.documents.v3alpha.Resources.ListCitations:input_type -> com.seed.documents.v3alpha.ListCitationsRequest
	5,  // 18: com.seed.documents.v3alpha.Resources.PushResourcesToPeer:input_type -> com.seed.documents.v3alpha.PushResourcesToPeerRequest
	4,  // 19: com.seed.documents.v3alpha.Resources.GetResource:output_type -> com.seed.documents.v3alpha.Resource
	10, // 20: com.seed.documents.v3alpha.Resources.DiscoverResource:output_type -> com.seed.documents.v3alpha.DiscoverResourceResponse
	14, // 21: com.seed.documents.v3alpha.Resources.SearchResources:output_type -> com.seed.documents.v3alpha.SearchResourcesResponse
	7,  // 22: com.seed.documents.v3alpha.Resources.ListCitations:output_type -> com.seed.documents.v3alpha.ListCitationsResponse
	20, // 23: com.seed.documents.v3alpha.Resources.PushResourcesToPeer:output_type -> com.seed.p2p.v1alpha.AnnounceBlobsProgress
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_documents_v3alpha_resources_proto_init() }
func file_documents_v3alpha_resources_proto_init() {
	if File_documents_v3alpha_resources_proto != nil {
		return
	}
	file_documents_v3alpha_documents_proto_init()
	file_documents_v3alpha_comments_proto_init()
	file_documents_v3alpha_resources_proto_msgTypes[1].OneofWrappers = []any{
		(*Resource_Document)(nil),
		(*Resource_Comment)(nil),
		(*Resource_Contact)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_documents_v3alpha_resources_proto_rawDesc), len(file_documents_v3alpha_resources_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_documents_v3alpha_resources_proto_goTypes,
		DependencyIndexes: file_documents_v3alpha_resources_proto_depIdxs,
		EnumInfos:         file_documents_v3alpha_resources_proto_enumTypes,
		MessageInfos:      file_documents_v3alpha_resources_proto_msgTypes,
	}.Build()
	File_documents_v3alpha_resources_proto = out.File
	file_documents_v3alpha_resources_proto_goTypes = nil
	file_documents_v3alpha_resources_proto_depIdxs = nil
}
