basePath: /
host: pay.seedhypermedia.com
info:
  contact:
    email: team@seedhypermedia.com
    name: seed hypermedia
    url: https://seedhypermedia.com
  description: Payments server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Seed Hypermedia PAY
  version: 0.0.1
paths: {}
swagger: "2.0"
