name: seed-monitoring
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3001"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"

  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"
    volumes:
      - alloy-data:/var/lib/alloy/data
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/alloy/config.alloy"

volumes:
  grafana-data: {}
  prometheus-data: {}
  alloy-data: {}
