/**
 * App-side crypto helpers.
 *
 * The vault key-derivation and XChaCha20-Poly1305 primitives live in the
 * shared client SDK (`@seed-hypermedia/client`) — re-exported here under the
 * app's historical import path. Only browser-specific helpers (WebAuthn, PRF,
 * recovery words, random generation) are implemented locally.
 */

import * as bip39 from '@scure/bip39'
import * as english from '@scure/bip39/wordlists/english.js'
import * as vaultCrypto from '@seed-hypermedia/client/vault'

export {decrypt, encrypt} from '@seed-hypermedia/client/encryption'
export {deriveAuthKey, deriveEncryptionKey, deriveSecretCredentialAuthKey} from '@seed-hypermedia/client/vault'

/** Number of recovery words: a 128-bit English BIP-39 mnemonic. */
export const RECOVERY_WORD_COUNT = 12

/** Generate fresh recovery words for a new account. */
export function generateRecoveryWords(): string[] {
  return bip39.generateMnemonic(english.wordlist, 128).split(' ')
}

/**
 * Whether the words form a valid recovery phrase.
 * All known words, and the BIP-39 checksum passes.
 */
export function isValidRecoveryPhrase(words: string[]): boolean {
  return words.length === RECOVERY_WORD_COUNT && bip39.validateMnemonic(words.join(' '), english.wordlist)
}

/**
 * Derive the recovery credential's secret from the recovery words. The words encode 128 bits of
 * entropy; HKDF stretches it into the 32-byte secret that, like any secret credential, wraps the
 * DEK and derives the credential's auth key. Throws if the phrase is invalid.
 */
export async function deriveRecoverySecret(words: string[]): Promise<Uint8Array> {
  const entropy = bip39.mnemonicToEntropy(words.join(' '), english.wordlist)
  return vaultCrypto.deriveHKDFKey(new Uint8Array(entropy), 'seed-hypermedia-vault-recovery-secret')
}

const RECOVERY_DOCUMENT_HEADER = 'Hypermedia recovery words'

/**
 * Plain-text recovery document the user downloads at sign-up.
 * Readable on its own, and laid out for `parseRecoveryDocument`.
 */
export function formatRecoveryDocument(words: readonly string[], email: string): string {
  return [
    RECOVERY_DOCUMENT_HEADER,
    email ? `Account: ${email}` : '',
    '',
    ...words.map((word, i) => `${i + 1}. ${word}`),
    '',
    'If you forget your password, enter these words or upload this file to recover your account.',
    'Keep them somewhere safe and private. Hypermedia does not have access to them.',
    'DO NOT EDIT THIS FILE.',
  ].join('\n')
}

/**
 * Read the recovery words back from a document made by `formatRecoveryDocument`. Returns null
 * unless the file starts with the header and has exactly one `N. word` line for each position.
 */
export function parseRecoveryDocument(text: string): string[] | null {
  const lines = text.split(/\r?\n/).map((line) => line.trim())
  if (lines.find((line) => line) !== RECOVERY_DOCUMENT_HEADER) return null

  const words: string[] = Array(RECOVERY_WORD_COUNT).fill('')
  for (const line of lines) {
    const match = /^(\d+)\.\s+(\S+)$/.exec(line)
    if (!match) continue
    const index = Number(match[1]) - 1
    if (index < 0 || index >= RECOVERY_WORD_COUNT || words[index]) return null
    words[index] = match[2]!.toLowerCase()
  }
  return words.every((word) => word) ? words : null
}

/**
 * Generate a random password salt for Argon2id.
 */
export function generatePasswordSalt(): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(16))
}

/**
 * Generate a random Data Encryption Key (64 bytes).
 */
export function generateDEK(): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(64))
}

/**
 * Generate a random nonce for XChaCha20-Poly1305 (24 bytes).
 */
export function generateNonce(): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(24))
}

/**
 * Requirements a new password must meet, shown as a live checklist while the user types.
 */
export function getPasswordRules(password: string): {label: string; met: boolean}[] {
  return [
    {label: 'At least 8 characters', met: password.length >= 8},
    {label: 'One uppercase letter', met: /[A-Z]/.test(password)},
    {label: 'One number or special character', met: /[^A-Za-z]/.test(password)},
  ]
}

/**
 * Check if WebAuthn is supported.
 */
export function isWebAuthnSupported(): boolean {
  return !!(window.PublicKeyCredential && typeof window.PublicKeyCredential === 'function')
}

/**
 * Check if platform authenticator is available.
 */
export async function isPlatformAuthenticatorAvailable(): Promise<boolean> {
  if (!isWebAuthnSupported()) return false
  if (typeof window.PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable !== 'function') return false

  try {
    return await window.PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable()
  } catch {
    return false
  }
}

/**
 * Fixed PRF salt for WebAuthn key derivation.
 * Since each credential has a unique internal secret, a fixed salt still produces
 * unique derived keys per credential. This simplifies the implementation by avoiding
 * per-credential salt storage on the server.
 */
export const PRF_SALT = new TextEncoder().encode('hypermedia-identity-vault-v1')

/**
 * PRF extension result type (not included in TypeScript's built-in types).
 */
export interface PRFOutput {
  results?: {
    first?: ArrayBuffer
    second?: ArrayBuffer
  }
  enabled?: boolean
}

/**
 * Extract the wrapKey from PRF extension results.
 * The PRF output is 32 bytes, which is used directly as the wrapKey.
 * Returns null if PRF is not supported or the result is missing.
 */
export function extractPRFKey(prfOutput: PRFOutput | undefined): Uint8Array | null {
  if (!prfOutput?.results?.first) {
    return null
  }
  return new Uint8Array(prfOutput.results.first)
}
