{
 "title": "Seed Desktop Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"seed-daemon|electron\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime (Last or Current)",
   "type": "stat",
   "description": "Shows the current uptime if the program is running. Otherwise shows the uptime from the last run.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=~\"seed-daemon|electron\", instance=~\"$instance\"}) and on (job, instance) (up == 1)",
     "legendFormat": "{{instance}} – {{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage over a time window. Measured as number of CPU cores being used, because we want to monitor behavior of the program, not the performance of the machine.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "cores/s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"seed-daemon|electron\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} – {{job}}"
    },
    {
     "expr": "sum by (instance) (rate(process_cpu_seconds_total{job=~\"seed-daemon|electron\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} – Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"seed-daemon|electron\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} – {{job}}"
    },
    {
     "expr": "sum by (instance) (process_resident_memory_bytes{job=~\"seed-daemon|electron\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} – Total"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "May not be supported on all platforms.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(process_disk_read_bytes_total{job=\"seed-daemon\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} – Reads"
    },
    {
     "expr": "rate(process_disk_written_bytes_total{job=\"seed-daemon\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} – Writes"
    }
   ]
  },
  { "title": "seed-daemon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Libp2p Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "libp2p_open_connections{job=\"seed-daemon\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}} – Open Connections"
    }
   ]
  },
  {
   "title": "IPFS Blockstore Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(seed_ipfs_blockstore_calls_total{job=~\"seed-daemon\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} – {{method}}"
    }
   ]
  },
  {
   "title": "Top 10 HTTP Requests (Over 5m)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "topk(10, rate(seed_http_request_duration_seconds_count{job=\"seed-daemon\", instance=~\"$instance\"}[5m])*60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQLite Queries Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "rate(seed_sqlite_queries_total{job=\"seed-daemon\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} – Queries"
    }
   ]
  }
 ]
}