// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.24.4
// source: daemon/v1alpha/daemon.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State describes various states of the daemon.
type State int32

const (
	// Daemon in starting up and it not ready to use yet.
	State_STARTING State = 0
	// Daemon is running a data migration, which may take a while.
	// Callers should poll and wait until the daemon becomes ACTIVE.
	State_MIGRATING State = 1
	// Daemon is active and ready to use.
	State_ACTIVE State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "STARTING",
		1: "MIGRATING",
		3: "ACTIVE",
	}
	State_value = map[string]int32{
		"STARTING":  0,
		"MIGRATING": 1,
		"ACTIVE":    3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_v1alpha_daemon_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_daemon_v1alpha_daemon_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{0}
}

// Different types of tasks that the daemon can perform.
type TaskName int32

const (
	// Unknown task.
	TaskName_TASK_NAME_UNSPECIFIED TaskName = 0
	// Task for reindexing the database.
	TaskName_REINDEXING TaskName = 1
	// Task for generating embeddings.
	TaskName_EMBEDDING TaskName = 2
	// Task for loading a machine learning model.
	TaskName_LOADING_MODEL TaskName = 3
)

// Enum value maps for TaskName.
var (
	TaskName_name = map[int32]string{
		0: "TASK_NAME_UNSPECIFIED",
		1: "REINDEXING",
		2: "EMBEDDING",
		3: "LOADING_MODEL",
	}
	TaskName_value = map[string]int32{
		"TASK_NAME_UNSPECIFIED": 0,
		"REINDEXING":            1,
		"EMBEDDING":             2,
		"LOADING_MODEL":         3,
	}
)

func (x TaskName) Enum() *TaskName {
	p := new(TaskName)
	*p = x
	return p
}

func (x TaskName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskName) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_v1alpha_daemon_proto_enumTypes[1].Descriptor()
}

func (TaskName) Type() protoreflect.EnumType {
	return &file_daemon_v1alpha_daemon_proto_enumTypes[1]
}

func (x TaskName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskName.Descriptor instead.
func (TaskName) EnumDescriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{1}
}

// Request to generate mnemonic words.
type GenMnemonicRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Number of mnemonic words to encode the seed.
	// Usually 12 or 24 words.
	// By default 12 words are generated.
	WordCount     int32 `protobuf:"varint,1,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenMnemonicRequest) Reset() {
	*x = GenMnemonicRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenMnemonicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenMnemonicRequest) ProtoMessage() {}

func (x *GenMnemonicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenMnemonicRequest.ProtoReflect.Descriptor instead.
func (*GenMnemonicRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *GenMnemonicRequest) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

// Response with the generated mnemonic.
type GenMnemonicResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of human-friendly words that can be used to backup the seed. These
	// words must be stored in a secret place by the user.
	Mnemonic      []string `protobuf:"bytes,1,rep,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenMnemonicResponse) Reset() {
	*x = GenMnemonicResponse{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenMnemonicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenMnemonicResponse) ProtoMessage() {}

func (x *GenMnemonicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenMnemonicResponse.ProtoReflect.Descriptor instead.
func (*GenMnemonicResponse) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{1}
}

func (x *GenMnemonicResponse) GetMnemonic() []string {
	if x != nil {
		return x.Mnemonic
	}
	return nil
}

// Request to register a new account key derived from the mnemonic.
type RegisterKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The list of BIP-39 mnemonic words.
	Mnemonic []string `protobuf:"bytes,1,rep,name=mnemonic,proto3" json:"mnemonic,omitempty"`
	// Optional. Passphrase for the seed.
	Passphrase string `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	// Required. Private name/label for the signing key, to easily identify keys when they are more than one.
	// Name must be unique across all the registered keys.
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterKeyRequest) Reset() {
	*x = RegisterKeyRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterKeyRequest) ProtoMessage() {}

func (x *RegisterKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterKeyRequest.ProtoReflect.Descriptor instead.
func (*RegisterKeyRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterKeyRequest) GetMnemonic() []string {
	if x != nil {
		return x.Mnemonic
	}
	return nil
}

func (x *RegisterKeyRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

func (x *RegisterKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to import an existing account key from a .hmkey.json file path.
type ImportKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Absolute path to a .hmkey.json key export file.
	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// Optional. Password to decrypt encrypted key exports.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportKeyRequest) Reset() {
	*x = ImportKeyRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportKeyRequest) ProtoMessage() {}

func (x *ImportKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportKeyRequest.ProtoReflect.Descriptor instead.
func (*ImportKeyRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{3}
}

func (x *ImportKeyRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ImportKeyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Request to export an existing account key to a .hmkey.json file path.
type ExportKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Name of the key to export.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required. Absolute path to a .hmkey.json key export file.
	FilePath string `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	// Optional. Password to encrypt the exported key file.
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportKeyRequest) Reset() {
	*x = ExportKeyRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportKeyRequest) ProtoMessage() {}

func (x *ExportKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportKeyRequest.ProtoReflect.Descriptor instead.
func (*ExportKeyRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{4}
}

func (x *ExportKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportKeyRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ExportKeyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Request to get basic information about the running daemon.
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{5}
}

// Request to force the syncing process.
type ForceSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceSyncRequest) Reset() {
	*x = ForceSyncRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceSyncRequest) ProtoMessage() {}

func (x *ForceSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceSyncRequest.ProtoReflect.Descriptor instead.
func (*ForceSyncRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{6}
}

// Request to force reindexing of the entire database.
type ForceReindexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceReindexRequest) Reset() {
	*x = ForceReindexRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceReindexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceReindexRequest) ProtoMessage() {}

func (x *ForceReindexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceReindexRequest.ProtoReflect.Descriptor instead.
func (*ForceReindexRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{7}
}

// Response after forcing reindexing.
type ForceReindexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceReindexResponse) Reset() {
	*x = ForceReindexResponse{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceReindexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceReindexResponse) ProtoMessage() {}

func (x *ForceReindexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceReindexResponse.ProtoReflect.Descriptor instead.
func (*ForceReindexResponse) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{8}
}

// Request to delete all keys.
type DeleteAllKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAllKeysRequest) Reset() {
	*x = DeleteAllKeysRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAllKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAllKeysRequest) ProtoMessage() {}

func (x *DeleteAllKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAllKeysRequest.ProtoReflect.Descriptor instead.
func (*DeleteAllKeysRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{9}
}

// Request to list signing keys.
type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{10}
}

// Response with the list of registered signing keys.
type ListKeysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of registered keys.
	Keys          []*NamedKey `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{11}
}

func (x *ListKeysResponse) GetKeys() []*NamedKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// Request to change the key name.
type UpdateKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current name of the key.
	CurrentName string `protobuf:"bytes,1,opt,name=current_name,json=currentName,proto3" json:"current_name,omitempty"`
	// New name for the key.
	NewName       string `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeyRequest) Reset() {
	*x = UpdateKeyRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeyRequest) ProtoMessage() {}

func (x *UpdateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeyRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeyRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateKeyRequest) GetCurrentName() string {
	if x != nil {
		return x.CurrentName
	}
	return ""
}

func (x *UpdateKeyRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// Request to delete an existing key.
type DeleteKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the key to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to store blobs.
type StoreBlobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. List of blobs to be stored.
	// The request is atomic: either all blobs are stored or none of them.
	Blobs         []*Blob `protobuf:"bytes,1,rep,name=blobs,proto3" json:"blobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBlobsRequest) Reset() {
	*x = StoreBlobsRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBlobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlobsRequest) ProtoMessage() {}

func (x *StoreBlobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlobsRequest.ProtoReflect.Descriptor instead.
func (*StoreBlobsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{14}
}

func (x *StoreBlobsRequest) GetBlobs() []*Blob {
	if x != nil {
		return x.Blobs
	}
	return nil
}

// Response after storing blobs.
type StoreBlobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of CIDs for the stored blobs.
	// The order is the same as in the request.
	Cids          []string `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBlobsResponse) Reset() {
	*x = StoreBlobsResponse{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBlobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBlobsResponse) ProtoMessage() {}

func (x *StoreBlobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBlobsResponse.ProtoReflect.Descriptor instead.
func (*StoreBlobsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{15}
}

func (x *StoreBlobsResponse) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

// Request to create a new device link session.
type CreateDeviceLinkSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Name of the signing key for which to create the delegation.
	SigningKeyName string `protobuf:"bytes,1,opt,name=signing_key_name,json=signingKeyName,proto3" json:"signing_key_name,omitempty"`
	// Optional. Label that will be used for the newly created capability.
	// The label is publicly visible.
	Label         string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceLinkSessionRequest) Reset() {
	*x = CreateDeviceLinkSessionRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceLinkSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceLinkSessionRequest) ProtoMessage() {}

func (x *CreateDeviceLinkSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceLinkSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceLinkSessionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{16}
}

func (x *CreateDeviceLinkSessionRequest) GetSigningKeyName() string {
	if x != nil {
		return x.SigningKeyName
	}
	return ""
}

func (x *CreateDeviceLinkSessionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Request to get the device link session.
type GetDeviceLinkSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceLinkSessionRequest) Reset() {
	*x = GetDeviceLinkSessionRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceLinkSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceLinkSessionRequest) ProtoMessage() {}

func (x *GetDeviceLinkSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceLinkSessionRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceLinkSessionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{17}
}

// Request to sign data.
type SignDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Name of the signing key to use for signing.
	SigningKeyName string `protobuf:"bytes,1,opt,name=signing_key_name,json=signingKeyName,proto3" json:"signing_key_name,omitempty"`
	// Required. Data to be signed.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDataRequest) Reset() {
	*x = SignDataRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDataRequest) ProtoMessage() {}

func (x *SignDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDataRequest.ProtoReflect.Descriptor instead.
func (*SignDataRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{18}
}

func (x *SignDataRequest) GetSigningKeyName() string {
	if x != nil {
		return x.SigningKeyName
	}
	return ""
}

func (x *SignDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Response for signing data.
type SignDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signature over the data.
	Signature     []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignDataResponse) Reset() {
	*x = SignDataResponse{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDataResponse) ProtoMessage() {}

func (x *SignDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDataResponse.ProtoReflect.Descriptor instead.
func (*SignDataResponse) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{19}
}

func (x *SignDataResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Information about the device link session.
type DeviceLinkSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dial information for the node.
	AddrInfo *AddrInfo `protobuf:"bytes,1,opt,name=addr_info,json=addrInfo,proto3" json:"addr_info,omitempty"`
	// Secret token for the linking session.
	SecretToken string `protobuf:"bytes,2,opt,name=secret_token,json=secretToken,proto3" json:"secret_token,omitempty"`
	// Account ID that wants to link the new device.
	AccountId string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Label for the future capability as defined by the user.
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// Expiration time of the session.
	ExpireTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	// Optional. Time when the session was redeemed,
	// i.e. when the device link exchange was completed successfully.
	RedeemTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=redeem_time,json=redeemTime,proto3" json:"redeem_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceLinkSession) Reset() {
	*x = DeviceLinkSession{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceLinkSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceLinkSession) ProtoMessage() {}

func (x *DeviceLinkSession) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceLinkSession.ProtoReflect.Descriptor instead.
func (*DeviceLinkSession) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{20}
}

func (x *DeviceLinkSession) GetAddrInfo() *AddrInfo {
	if x != nil {
		return x.AddrInfo
	}
	return nil
}

func (x *DeviceLinkSession) GetSecretToken() string {
	if x != nil {
		return x.SecretToken
	}
	return ""
}

func (x *DeviceLinkSession) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeviceLinkSession) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DeviceLinkSession) GetExpireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireTime
	}
	return nil
}

func (x *DeviceLinkSession) GetRedeemTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RedeemTime
	}
	return nil
}

// Address information about a single peer.
type AddrInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddrInfo) Reset() {
	*x = AddrInfo{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrInfo) ProtoMessage() {}

func (x *AddrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrInfo.ProtoReflect.Descriptor instead.
func (*AddrInfo) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{21}
}

func (x *AddrInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AddrInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// Raw blob to be stored.
type Blob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. The client can provide a CID for the blob (the server will verify it).
	// If not provided, the data is assumed to be DAG-CBOR encoded, and the server will generate a CID
	// using its default hash function.
	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	// Required. Raw data of the blob.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blob) Reset() {
	*x = Blob{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blob) ProtoMessage() {}

func (x *Blob) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blob.ProtoReflect.Descriptor instead.
func (*Blob) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{22}
}

func (x *Blob) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Blob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Info is a generic information about the running node.
type Info struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current state of the daemon.
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=com.seed.daemon.v1alpha.State" json:"state,omitempty"`
	// Libp2p Peer ID of this node.
	PeerId string `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Start time of the node.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The libp2p protocol ID that the daemon is using.
	ProtocolId string `protobuf:"bytes,4,opt,name=protocol_id,json=protocolId,proto3" json:"protocol_id,omitempty"`
	// The tasks that the daemon is currently performing.
	Tasks         []*Task `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{23}
}

func (x *Info) GetState() State {
	if x != nil {
		return x.State
	}
	return State_STARTING
}

func (x *Info) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Info) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Info) GetProtocolId() string {
	if x != nil {
		return x.ProtocolId
	}
	return ""
}

func (x *Info) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

// Description of a task that the daemon is performing.
type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the task.
	TaskName TaskName `protobuf:"varint,1,opt,name=task_name,json=taskName,proto3,enum=com.seed.daemon.v1alpha.TaskName" json:"task_name,omitempty"`
	// Description of the task.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Total amount of work for the task.
	Total int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	// Amount of work completed. Always less than or equal to total.
	Completed     int64 `protobuf:"varint,4,opt,name=completed,proto3" json:"completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{24}
}

func (x *Task) GetTaskName() TaskName {
	if x != nil {
		return x.TaskName
	}
	return TaskName_TASK_NAME_UNSPECIFIED
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Task) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

// Signing key with an internal name.
type NamedKey struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key in Multikey format.
	// https://www.w3.org/TR/vc-data-integrity/#multikey.
	PublicKey string `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Private name for the key. Useful to identify the keys when there're more than one.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Account ID representation of this key.
	AccountId     string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedKey) Reset() {
	*x = NamedKey{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedKey) ProtoMessage() {}

func (x *NamedKey) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedKey.ProtoReflect.Descriptor instead.
func (*NamedKey) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{25}
}

func (x *NamedKey) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NamedKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedKey) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

// Request to get domain info.
type GetDomainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The domain name (e.g. "hyper.media").
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainRequest) Reset() {
	*x = GetDomainRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainRequest) ProtoMessage() {}

func (x *GetDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainRequest.ProtoReflect.Descriptor instead.
func (*GetDomainRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{26}
}

func (x *GetDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// Request to list tracked domains.
type ListDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{27}
}

// Response with the list of tracked domains.
type ListDomainsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of tracked domains.
	Domains       []*DomainInfo `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{28}
}

func (x *ListDomainsResponse) GetDomains() []*DomainInfo {
	if x != nil {
		return x.Domains
	}
	return nil
}

// Request to add a domain to track.
type AddDomainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The domain name (e.g. "hyper.media").
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDomainRequest) Reset() {
	*x = AddDomainRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDomainRequest) ProtoMessage() {}

func (x *AddDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDomainRequest.ProtoReflect.Descriptor instead.
func (*AddDomainRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{29}
}

func (x *AddDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// Request to remove a tracked domain.
type RemoveDomainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The domain name to remove.
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDomainRequest) Reset() {
	*x = RemoveDomainRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDomainRequest) ProtoMessage() {}

func (x *RemoveDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDomainRequest.ProtoReflect.Descriptor instead.
func (*RemoveDomainRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// Request to force a re-check of a domain.
type CheckDomainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The domain name to check.
	Domain        string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckDomainRequest) Reset() {
	*x = CheckDomainRequest{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckDomainRequest) ProtoMessage() {}

func (x *CheckDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckDomainRequest.ProtoReflect.Descriptor instead.
func (*CheckDomainRequest) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{31}
}

func (x *CheckDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

// Information about a tracked domain.
type DomainInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The domain name.
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Timestamp of the last check.
	LastCheck *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	// Status of the last check: "success", "unreachable", "error", or "unknown".
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Timestamp of the last successful check.
	LastSuccess *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	// The registered account UID from the domain's config.
	RegisteredAccountUid string `protobuf:"bytes,5,opt,name=registered_account_uid,json=registeredAccountUid,proto3" json:"registered_account_uid,omitempty"`
	// The peer ID of the domain's node.
	PeerId string `protobuf:"bytes,6,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Error details from the last failed check.
	LastError     string `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainInfo) Reset() {
	*x = DomainInfo{}
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainInfo) ProtoMessage() {}

func (x *DomainInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_v1alpha_daemon_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainInfo.ProtoReflect.Descriptor instead.
func (*DomainInfo) Descriptor() ([]byte, []int) {
	return file_daemon_v1alpha_daemon_proto_rawDescGZIP(), []int{32}
}

func (x *DomainInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainInfo) GetLastCheck() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheck
	}
	return nil
}

func (x *DomainInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DomainInfo) GetLastSuccess() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccess
	}
	return nil
}

func (x *DomainInfo) GetRegisteredAccountUid() string {
	if x != nil {
		return x.RegisteredAccountUid
	}
	return ""
}

func (x *DomainInfo) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DomainInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_daemon_v1alpha_daemon_proto protoreflect.FileDescriptor

const file_daemon_v1alpha_daemon_proto_rawDesc = "" +
	"\n" +
	"\x1bdaemon/v1alpha/daemon.proto\x12\x17com.seed.daemon.v1alpha\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\x12GenMnemonicRequest\x12\x1d\n" +
	"\n" +
	"word_count\x18\x01 \x01(\x05R\twordCount\"1\n" +
	"\x13GenMnemonicResponse\x12\x1a\n" +
	"\bmnemonic\x18\x01 \x03(\tR\bmnemonic\"d\n" +
	"\x12RegisterKeyRequest\x12\x1a\n" +
	"\bmnemonic\x18\x01 \x03(\tR\bmnemonic\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"K\n" +
	"\x10ImportKeyRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"_\n" +
	"\x10ExportKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"\x10\n" +
	"\x0eGetInfoRequest\"\x12\n" +
	"\x10ForceSyncRequest\"\x15\n" +
	"\x13ForceReindexRequest\"\x16\n" +
	"\x14ForceReindexResponse\"\x16\n" +
	"\x14DeleteAllKeysRequest\"\x11\n" +
	"\x0fListKeysRequest\"I\n" +
	"\x10ListKeysResponse\x125\n" +
	"\x04keys\x18\x01 \x03(\v2!.com.seed.daemon.v1alpha.NamedKeyR\x04keys\"P\n" +
	"\x10UpdateKeyRequest\x12!\n" +
	"\fcurrent_name\x18\x01 \x01(\tR\vcurrentName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"&\n" +
	"\x10DeleteKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"H\n" +
	"\x11StoreBlobsRequest\x123\n" +
	"\x05blobs\x18\x01 \x03(\v2\x1d.com.seed.daemon.v1alpha.BlobR\x05blobs\"(\n" +
	"\x12StoreBlobsResponse\x12\x12\n" +
	"\x04cids\x18\x01 \x03(\tR\x04cids\"`\n" +
	"\x1eCreateDeviceLinkSessionRequest\x12(\n" +
	"\x10signing_key_name\x18\x01 \x01(\tR\x0esigningKeyName\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x1d\n" +
	"\x1bGetDeviceLinkSessionRequest\"O\n" +
	"\x0fSignDataRequest\x12(\n" +
	"\x10signing_key_name\x18\x01 \x01(\tR\x0esigningKeyName\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"0\n" +
	"\x10SignDataResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"\xa5\x02\n" +
	"\x11DeviceLinkSession\x12>\n" +
	"\taddr_info\x18\x01 \x01(\v2!.com.seed.daemon.v1alpha.AddrInfoR\baddrInfo\x12!\n" +
	"\fsecret_token\x18\x02 \x01(\tR\vsecretToken\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12;\n" +
	"\vexpire_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expireTime\x12;\n" +
	"\vredeem_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"redeemTime\"9\n" +
	"\bAddrInfo\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\",\n" +
	"\x04Blob\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xe6\x01\n" +
	"\x04Info\x124\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1e.com.seed.daemon.v1alpha.StateR\x05state\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x1f\n" +
	"\vprotocol_id\x18\x04 \x01(\tR\n" +
	"protocolId\x123\n" +
	"\x05tasks\x18\x05 \x03(\v2\x1d.com.seed.daemon.v1alpha.TaskR\x05tasks\"\x9c\x01\n" +
	"\x04Task\x12>\n" +
	"\ttask_name\x18\x01 \x01(\x0e2!.com.seed.daemon.v1alpha.TaskNameR\btaskName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\x12\x1c\n" +
	"\tcompleted\x18\x04 \x01(\x03R\tcompleted\"\\\n" +
	"\bNamedKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\"*\n" +
	"\x10GetDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\x14\n" +
	"\x12ListDomainsRequest\"T\n" +
	"\x13ListDomainsResponse\x12=\n" +
	"\adomains\x18\x01 \x03(\v2#.com.seed.daemon.v1alpha.DomainInfoR\adomains\"*\n" +
	"\x10AddDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"-\n" +
	"\x13RemoveDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\",\n" +
	"\x12CheckDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\xa4\x02\n" +
	"\n" +
	"DomainInfo\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x129\n" +
	"\n" +
	"last_check\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tlastCheck\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12=\n" +
	"\flast_success\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastSuccess\x124\n" +
	"\x16registered_account_uid\x18\x05 \x01(\tR\x14registeredAccountUid\x12\x17\n" +
	"\apeer_id\x18\x06 \x01(\tR\x06peerId\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError*0\n" +
	"\x05State\x12\f\n" +
	"\bSTARTING\x10\x00\x12\r\n" +
	"\tMIGRATING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x03*W\n" +
	"\bTaskName\x12\x19\n" +
	"\x15TASK_NAME_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"REINDEXING\x10\x01\x12\r\n" +
	"\tEMBEDDING\x10\x02\x12\x11\n" +
	"\rLOADING_MODEL\x10\x032\x8d\x0f\n" +
	"\x06Daemon\x12h\n" +
	"\vGenMnemonic\x12+.com.seed.daemon.v1alpha.GenMnemonicRequest\x1a,.com.seed.daemon.v1alpha.GenMnemonicResponse\x12]\n" +
	"\vRegisterKey\x12+.com.seed.daemon.v1alpha.RegisterKeyRequest\x1a!.com.seed.daemon.v1alpha.NamedKey\x12Y\n" +
	"\tImportKey\x12).com.seed.daemon.v1alpha.ImportKeyRequest\x1a!.com.seed.daemon.v1alpha.NamedKey\x12N\n" +
	"\tExportKey\x12).com.seed.daemon.v1alpha.ExportKeyRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\aGetInfo\x12'.com.seed.daemon.v1alpha.GetInfoRequest\x1a\x1d.com.seed.daemon.v1alpha.Info\x12N\n" +
	"\tForceSync\x12).com.seed.daemon.v1alpha.ForceSyncRequest\x1a\x16.google.protobuf.Empty\x12k\n" +
	"\fForceReindex\x12,.com.seed.daemon.v1alpha.ForceReindexRequest\x1a-.com.seed.daemon.v1alpha.ForceReindexResponse\x12_\n" +
	"\bListKeys\x12(.com.seed.daemon.v1alpha.ListKeysRequest\x1a).com.seed.daemon.v1alpha.ListKeysResponse\x12Y\n" +
	"\tUpdateKey\x12).com.seed.daemon.v1alpha.UpdateKeyRequest\x1a!.com.seed.daemon.v1alpha.NamedKey\x12N\n" +
	"\tDeleteKey\x12).com.seed.daemon.v1alpha.DeleteKeyRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\rDeleteAllKeys\x12-.com.seed.daemon.v1alpha.DeleteAllKeysRequest\x1a\x16.google.protobuf.Empty\x12e\n" +
	"\n" +
	"StoreBlobs\x12*.com.seed.daemon.v1alpha.StoreBlobsRequest\x1a+.com.seed.daemon.v1alpha.StoreBlobsResponse\x12~\n" +
	"\x17CreateDeviceLinkSession\x127.com.seed.daemon.v1alpha.CreateDeviceLinkSessionRequest\x1a*.com.seed.daemon.v1alpha.DeviceLinkSession\x12x\n" +
	"\x14GetDeviceLinkSession\x124.com.seed.daemon.v1alpha.GetDeviceLinkSessionRequest\x1a*.com.seed.daemon.v1alpha.DeviceLinkSession\x12_\n" +
	"\bSignData\x12(.com.seed.daemon.v1alpha.SignDataRequest\x1a).com.seed.daemon.v1alpha.SignDataResponse\x12[\n" +
	"\tGetDomain\x12).com.seed.daemon.v1alpha.GetDomainRequest\x1a#.com.seed.daemon.v1alpha.DomainInfo\x12h\n" +
	"\vListDomains\x12+.com.seed.daemon.v1alpha.ListDomainsRequest\x1a,.com.seed.daemon.v1alpha.ListDomainsResponse\x12[\n" +
	"\tAddDomain\x12).com.seed.daemon.v1alpha.AddDomainRequest\x1a#.com.seed.daemon.v1alpha.DomainInfo\x12T\n" +
	"\fRemoveDomain\x12,.com.seed.daemon.v1alpha.RemoveDomainRequest\x1a\x16.google.protobuf.Empty\x12_\n" +
	"\vCheckDomain\x12+.com.seed.daemon.v1alpha.CheckDomainRequest\x1a#.com.seed.daemon.v1alpha.DomainInfoB-Z+seed/backend/genproto/daemon/v1alpha;daemonb\x06proto3"

var (
	file_daemon_v1alpha_daemon_proto_rawDescOnce sync.Once
	file_daemon_v1alpha_daemon_proto_rawDescData []byte
)

func file_daemon_v1alpha_daemon_proto_rawDescGZIP() []byte {
	file_daemon_v1alpha_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_v1alpha_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_v1alpha_daemon_proto_rawDesc), len(file_daemon_v1alpha_daemon_proto_rawDesc)))
	})
	return file_daemon_v1alpha_daemon_proto_rawDescData
}

var file_daemon_v1alpha_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_daemon_v1alpha_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_daemon_v1alpha_daemon_proto_goTypes = []any{
	(State)(0),                             // 0: com.seed.daemon.v1alpha.State
	(TaskName)(0),                          // 1: com.seed.daemon.v1alpha.TaskName
	(*GenMnemonicRequest)(nil),             // 2: com.seed.daemon.v1alpha.GenMnemonicRequest
	(*GenMnemonicResponse)(nil),            // 3: com.seed.daemon.v1alpha.GenMnemonicResponse
	(*RegisterKeyRequest)(nil),             // 4: com.seed.daemon.v1alpha.RegisterKeyRequest
	(*ImportKeyRequest)(nil),               // 5: com.seed.daemon.v1alpha.ImportKeyRequest
	(*ExportKeyRequest)(nil),               // 6: com.seed.daemon.v1alpha.ExportKeyRequest
	(*GetInfoRequest)(nil),                 // 7: com.seed.daemon.v1alpha.GetInfoRequest
	(*ForceSyncRequest)(nil),               // 8: com.seed.daemon.v1alpha.ForceSyncRequest
	(*ForceReindexRequest)(nil),            // 9: com.seed.daemon.v1alpha.ForceReindexRequest
	(*ForceReindexResponse)(nil),           // 10: com.seed.daemon.v1alpha.ForceReindexResponse
	(*DeleteAllKeysRequest)(nil),           // 11: com.seed.daemon.v1alpha.DeleteAllKeysRequest
	(*ListKeysRequest)(nil),                // 12: com.seed.daemon.v1alpha.ListKeysRequest
	(*ListKeysResponse)(nil),               // 13: com.seed.daemon.v1alpha.ListKeysResponse
	(*UpdateKeyRequest)(nil),               // 14: com.seed.daemon.v1alpha.UpdateKeyRequest
	(*DeleteKeyRequest)(nil),               // 15: com.seed.daemon.v1alpha.DeleteKeyRequest
	(*StoreBlobsRequest)(nil),              // 16: com.seed.daemon.v1alpha.StoreBlobsRequest
	(*StoreBlobsResponse)(nil),             // 17: com.seed.daemon.v1alpha.StoreBlobsResponse
	(*CreateDeviceLinkSessionRequest)(nil), // 18: com.seed.daemon.v1alpha.CreateDeviceLinkSessionRequest
	(*GetDeviceLinkSessionRequest)(nil),    // 19: com.seed.daemon.v1alpha.GetDeviceLinkSessionRequest
	(*SignDataRequest)(nil),                // 20: com.seed.daemon.v1alpha.SignDataRequest
	(*SignDataResponse)(nil),               // 21: com.seed.daemon.v1alpha.SignDataResponse
	(*DeviceLinkSession)(nil),              // 22: com.seed.daemon.v1alpha.DeviceLinkSession
	(*AddrInfo)(nil),                       // 23: com.seed.daemon.v1alpha.AddrInfo
	(*Blob)(nil),                           // 24: com.seed.daemon.v1alpha.Blob
	(*Info)(nil),                           // 25: com.seed.daemon.v1alpha.Info
	(*Task)(nil),                           // 26: com.seed.daemon.v1alpha.Task
	(*NamedKey)(nil),                       // 27: com.seed.daemon.v1alpha.NamedKey
	(*GetDomainRequest)(nil),               // 28: com.seed.daemon.v1alpha.GetDomainRequest
	(*ListDomainsRequest)(nil),             // 29: com.seed.daemon.v1alpha.ListDomainsRequest
	(*ListDomainsResponse)(nil),            // 30: com.seed.daemon.v1alpha.ListDomainsResponse
	(*AddDomainRequest)(nil),               // 31: com.seed.daemon.v1alpha.AddDomainRequest
	(*RemoveDomainRequest)(nil),            // 32: com.seed.daemon.v1alpha.RemoveDomainRequest
	(*CheckDomainRequest)(nil),             // 33: com.seed.daemon.v1alpha.CheckDomainRequest
	(*DomainInfo)(nil),                     // 34: com.seed.daemon.v1alpha.DomainInfo
	(*timestamppb.Timestamp)(nil),          // 35: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 36: google.protobuf.Empty
}
var file_daemon_v1alpha_daemon_proto_depIdxs = []int32{
	27, // 0: com.seed.daemon.v1alpha.ListKeysResponse.keys:type_name -> com.seed.daemon.v1alpha.NamedKey
	24, // 1: com.seed.daemon.v1alpha.StoreBlobsRequest.blobs:type_name -> com.seed.daemon.v1alpha.Blob
	23, // 2: com.seed.daemon.v1alpha.DeviceLinkSession.addr_info:type_name -> com.seed.daemon.v1alpha.AddrInfo
	35, // 3: com.seed.daemon.v1alpha.DeviceLinkSession.expire_time:type_name -> google.protobuf.Timestamp
	35, // 4: com.seed.daemon.v1alpha.DeviceLinkSession.redeem_time:type_name -> google.protobuf.Timestamp
	0,  // 5: com.seed.daemon.v1alpha.Info.state:type_name -> com.seed.daemon.v1alpha.State
	35, // 6: com.seed.daemon.v1alpha.Info.start_time:type_name -> google.protobuf.Timestamp
	26, // 7: com.seed.daemon.v1alpha.Info.tasks:type_name -> com.seed.daemon.v1alpha.Task
	1,  // 8: com.seed.daemon.v1alpha.Task.task_name:type_name -> com.seed.daemon.v1alpha.TaskName
	34, // 9: com.seed.daemon.v1alpha.ListDomainsResponse.domains:type_name -> com.seed.daemon.v1alpha.DomainInfo
	35, // 10: com.seed.daemon.v1alpha.DomainInfo.last_check:type_name -> google.protobuf.Timestamp
	35, // 11: com.seed.daemon.v1alpha.DomainInfo.last_success:type_name -> google.protobuf.Timestamp
	2,  // 12: com.seed.daemon.v1alpha.Daemon.GenMnemonic:input_type -> com.seed.daemon.v1alpha.GenMnemonicRequest
	4,  // 13: com.seed.daemon.v1alpha.Daemon.RegisterKey:input_type -> com.seed.daemon.v1alpha.RegisterKeyRequest
	5,  // 14: com.seed.daemon.v1alpha.Daemon.ImportKey:input_type -> com.seed.daemon.v1alpha.ImportKeyRequest
	6,  // 15: com.seed.daemon.v1alpha.Daemon.ExportKey:input_type -> com.seed.daemon.v1alpha.ExportKeyRequest
	7,  // 16: com.seed.daemon.v1alpha.Daemon.GetInfo:input_type -> com.seed.daemon.v1alpha.GetInfoRequest
	8,  // 17: com.seed.daemon.v1alpha.Daemon.ForceSync:input_type -> com.seed.daemon.v1alpha.ForceSyncRequest
	9,  // 18: com.seed.daemon.v1alpha.Daemon.ForceReindex:input_type -> com.seed.daemon.v1alpha.ForceReindexRequest
	12, // 19: com.seed.daemon.v1alpha.Daemon.ListKeys:input_type -> com.seed.daemon.v1alpha.ListKeysRequest
	14, // 20: com.seed.daemon.v1alpha.Daemon.UpdateKey:input_type -> com.seed.daemon.v1alpha.UpdateKeyRequest
	15, // 21: com.seed.daemon.v1alpha.Daemon.DeleteKey:input_type -> com.seed.daemon.v1alpha.DeleteKeyRequest
	11, // 22: com.seed.daemon.v1alpha.Daemon.DeleteAllKeys:input_type -> com.seed.daemon.v1alpha.DeleteAllKeysRequest
	16, // 23: com.seed.daemon.v1alpha.Daemon.StoreBlobs:input_type -> com.seed.daemon.v1alpha.StoreBlobsRequest
	18, // 24: com.seed.daemon.v1alpha.Daemon.CreateDeviceLinkSession:input_type -> com.seed.daemon.v1alpha.CreateDeviceLinkSessionRequest
	19, // 25: com.seed.daemon.v1alpha.Daemon.GetDeviceLinkSession:input_type -> com.seed.daemon.v1alpha.GetDeviceLinkSessionRequest
	20, // 26: com.seed.daemon.v1alpha.Daemon.SignData:input_type -> com.seed.daemon.v1alpha.SignDataRequest
	28, // 27: com.seed.daemon.v1alpha.Daemon.GetDomain:input_type -> com.seed.daemon.v1alpha.GetDomainRequest
	29, // 28: com.seed.daemon.v1alpha.Daemon.ListDomains:input_type -> com.seed.daemon.v1alpha.ListDomainsRequest
	31, // 29: com.seed.daemon.v1alpha.Daemon.AddDomain:input_type -> com.seed.daemon.v1alpha.AddDomainRequest
	32, // 30: com.seed.daemon.v1alpha.Daemon.RemoveDomain:input_type -> com.seed.daemon.v1alpha.RemoveDomainRequest
	33, // 31: com.seed.daemon.v1alpha.Daemon.CheckDomain:input_type -> com.seed.daemon.v1alpha.CheckDomainRequest
	3,  // 32: com.seed.daemon.v1alpha.Daemon.GenMnemonic:output_type -> com.seed.daemon.v1alpha.GenMnemonicResponse
	27, // 33: com.seed.daemon.v1alpha.Daemon.RegisterKey:output_type -> com.seed.daemon.v1alpha.NamedKey
	27, // 34: com.seed.daemon.v1alpha.Daemon.ImportKey:output_type -> com.seed.daemon.v1alpha.NamedKey
	36, // 35: com.seed.daemon.v1alpha.Daemon.ExportKey:output_type -> google.protobuf.Empty
	25, // 36: com.seed.daemon.v1alpha.Daemon.GetInfo:output_type -> com.seed.daemon.v1alpha.Info
	36, // 37: com.seed.daemon.v1alpha.Daemon.ForceSync:output_type -> google.protobuf.Empty
	10, // 38: com.seed.daemon.v1alpha.Daemon.ForceReindex:output_type -> com.seed.daemon.v1alpha.ForceReindexResponse
	13, // 39: com.seed.daemon.v1alpha.Daemon.ListKeys:output_type -> com.seed.daemon.v1alpha.ListKeysResponse
	27, // 40: com.seed.daemon.v1alpha.Daemon.UpdateKey:output_type -> com.seed.daemon.v1alpha.NamedKey
	36, // 41: com.seed.daemon.v1alpha.Daemon.DeleteKey:output_type -> google.protobuf.Empty
	36, // 42: com.seed.daemon.v1alpha.Daemon.DeleteAllKeys:output_type -> google.protobuf.Empty
	17, // 43: com.seed.daemon.v1alpha.Daemon.StoreBlobs:output_type -> com.seed.daemon.v1alpha.StoreBlobsResponse
	22, // 44: com.seed.daemon.v1alpha.Daemon.CreateDeviceLinkSession:output_type -> com.seed.daemon.v1alpha.DeviceLinkSession
	22, // 45: com.seed.daemon.v1alpha.Daemon.GetDeviceLinkSession:output_type -> com.seed.daemon.v1alpha.DeviceLinkSession
	21, // 46: com.seed.daemon.v1alpha.Daemon.SignData:output_type -> com.seed.daemon.v1alpha.SignDataResponse
	34, // 47: com.seed.daemon.v1alpha.Daemon.GetDomain:output_type -> com.seed.daemon.v1alpha.DomainInfo
	30, // 48: com.seed.daemon.v1alpha.Daemon.ListDomains:output_type -> com.seed.daemon.v1alpha.ListDomainsResponse
	34, // 49: com.seed.daemon.v1alpha.Daemon.AddDomain:output_type -> com.seed.daemon.v1alpha.DomainInfo
	36, // 50: com.seed.daemon.v1alpha.Daemon.RemoveDomain:output_type -> google.protobuf.Empty
	34, // 51: com.seed.daemon.v1alpha.Daemon.CheckDomain:output_type -> com.seed.daemon.v1alpha.DomainInfo
	32, // [32:52] is the sub-list for method output_type
	12, // [12:32] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_daemon_v1alpha_daemon_proto_init() }
func file_daemon_v1alpha_daemon_proto_init() {
	if File_daemon_v1alpha_daemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_v1alpha_daemon_proto_rawDesc), len(file_daemon_v1alpha_daemon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_v1alpha_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_v1alpha_daemon_proto_depIdxs,
		EnumInfos:         file_daemon_v1alpha_daemon_proto_enumTypes,
		MessageInfos:      file_daemon_v1alpha_daemon_proto_msgTypes,
	}.Build()
	File_daemon_v1alpha_daemon_proto = out.File
	file_daemon_v1alpha_daemon_proto_goTypes = nil
	file_daemon_v1alpha_daemon_proto_depIdxs = nil
}
