name: Test Latest Release Check

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test-latest-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if latest release
        id: check_latest
        run: |
          latest_tag=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest \
            | jq -r '.tag_name')
          echo "Latest release tag: $latest_tag"
          echo "Current release tag: ${{ github.event.release.tag_name }}"

          if [[ "${latest_tag}" == "${{ github.event.release.tag_name }}" ]]; then
            echo "This IS the latest release"
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "This is NOT the latest release"
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi

        #   if [[ "${latest_tag}" == "2025.2.8" ]]; then
      - name: Show result
        run: |
          if [[ "${{ steps.check_latest.outputs.is_latest }}" == "true" ]]; then
            echo "✅ Confirmed: This is the latest release"
          else
            echo "❌ This is not the latest release"
          fi
